<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif;">

<h2>Cost Summary (Will take about 1-2 mins)</h2>
<form action="" method="post">
  <label for="textfield"></label>
  Date Begin:<input type="text" name="textfield" id="textfield" />
  Week Choice: Next 4 Weeks 
  <input name="" type="submit" />
</form>

</body>
</html>
