<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif;">
<h2>Stock Take List</h2>


<table width="650" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <th scope="col">BarCode</th>
    <th scope="col">Sales</th>
    <th scope="col">On Hand</th>
    <th scope="col">Act</th>
  </tr>
 <?php foreach ($this->arrResult as $key => $v){?> 
  <tr>
    <td><?=$v[0]?></td>
    <td><?=$v[1]?></td>
    <td><?=$v[2]?></td>
    <td>&nbsp;</td>
  </tr>
 <?php }?> 
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
</body>
</html>
