<form id="form1" name="form1" method="post" action="">
  <label for="textfield"></label>
  供货商全名
  : 
  <input type="text" name="name_supplier" id="name_supplier" />
  <br />
  <br />
  供货商缩写 :
  <input type="text" name="short_name_supplier" id="short_name_supplier" />
  <br />
  <br />
供货商位置 : 
<select name="location_supplier" id="location_supplier">
  <option value="CHINA">CHINA</option>
  <option value="AUSTRALIA">AUSTRALIA</option>
</select>
<br />
<br />
<input type="submit" name="button" id="button" value="Submit" />
<br />
  <br />
</form>
