<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Create New Sample</title>
</head>
<body>
<table width="600" border="1" cellspacing="2" cellpadding="2">
  <form id="form1" name="form1" method="post" action="/supplier/save-new-sample-step-a">
  <tr>
  	<td>录入人员姓名：
  	  <input type="text" name="staff_name" id="staff_name" /></td>	
  </tr>
  <tr>
    <td>供货商：
    <select name="id_supplier">
<?php
$suppliers = new Model_DbTable_Suppliers();
$slist = $suppliers->listAllSuppliers();

foreach ($slist as $key => $value){
?>
      <option value="<?php echo $value['id_supplier']?>"><?php echo $value['short_title']?></option>    
<?php
}
?>
    </select>
    点击此<a href="/supplier/add-supplier" target="_blank">链接</a>添加新供货商 </td>
  </tr>
  <tr>
    <td>产品中文名称(先不区分颜色):<br />      <input name="chinese_name" type="text" id="chinese_name" size="80" /></td>
  </tr>
  <tr>
    <td><p>样品颜色（当前阶段 无法补色：）</p> <br />
        <?php
    $colorCode = new Model_DbTable_Barcodecolorcodes();
	$clist = $colorCode->listAllColors();
	$counter = 0;
	foreach($clist as $key => $value){	
	?> 
        <input name="color_code[]" type="checkbox" value="<?php echo $value['id_color']?>" />
      
      <?php echo $value['des_color'];?>
    
    <?php
	$counter ++;
	if($counter%3 == 0){echo "<br/>";} 
	
	}
	?>   
    </td>
  </tr>
  <tr>
    <td>供货商条码(不区分颜色)：<input type="text" name="barcode_supplier" id="barcode_supplier" /> 
      <br />
      如果供货商条码 区分了不同的颜色， 请留白此处位置<br />
      <input type="submit" name="button" id="button" value="Submit" /></td>
  </tr>  
 </form>  
</table>
</body>
</html>
