<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body>
上传 样图：<br />
<form action="" method="post" name="form1"  enctype="multipart/form-data" >
<input type="hidden" name="is_thumb" value="1">
<input name="thumb_img" type="file" />
<input name="" type="submit" value="Submit" />
</form>
<br />
<br />
上传 大图压缩文件：
<form action="" method="post" name="form2"  enctype="multipart/form-data" >
<input type="hidden" name="is_zip" value="1">
<input name="img_zip" type="file" />
<input name="" type="submit" value="Submit" />
</form>
</body>
</html>