<?php



/**
 * 
 * @author
 * @link http://www.leadcasket.com/zend-model-generator/gen.php
 * ******************************************************************************
 * Please do not remove this block 
 * This class is generated by one page zend db table generator
 * ******************************************************************************
 *
 */

class Model_DbTable_Psattribute extends Zend_Db_Table_Abstract {

	protected $_name = 'ps_product_attribute';
	
	public function getPsattribute( $idProductAttribute){
		
		$row = $this->fetchRow("`id_product_attribute` = ". $idProductAttribute);
		if(!$row) return false;
		return $row->toArray();		
		
		}
		
	public function addPsattribute( $idProduct , $reference , $supplierReference , $location , $ean13 , $upc , $wholesalePrice , $price , $ecotax , $quantity , $weight , $unitPriceImpact , $defaultOn , $minimalQuantity){
		
		$data = array(
			
         "id_product" =>  $idProduct ,
         "reference" =>  $reference ,
         "supplier_reference" =>  $supplierReference ,
         "location" =>  $location ,
         "ean13" =>  $ean13 ,
         "upc" =>  $upc ,
         "wholesale_price" =>  $wholesalePrice ,
         "price" =>  $price ,
         "ecotax" =>  $ecotax ,
         "quantity" =>  $quantity ,
         "weight" =>  $weight ,
         "unit_price_impact" =>  $unitPriceImpact ,
         "default_on" =>  $defaultOn ,
         "minimal_quantity" =>  $minimalQuantity 
	
			);
		$this->insert($data);
		
		}
		
	public function updatePsattribute(  $idProductAttribute ,  $idProduct , $reference , $supplierReference , $location , $ean13 , $upc , $wholesalePrice , $price , $ecotax , $quantity , $weight , $unitPriceImpact , $defaultOn , $minimalQuantity){
		$data = array(
			
         "id_product" =>  $idProduct ,
         "reference" =>  $reference ,
         "supplier_reference" =>  $supplierReference ,
         "location" =>  $location ,
         "ean13" =>  $ean13 ,
         "upc" =>  $upc ,
         "wholesale_price" =>  $wholesalePrice ,
         "price" =>  $price ,
         "ecotax" =>  $ecotax ,
         "quantity" =>  $quantity ,
         "weight" =>  $weight ,
         "unit_price_impact" =>  $unitPriceImpact ,
         "default_on" =>  $defaultOn ,
         "minimal_quantity" =>  $minimalQuantity 
	
			);
			
		$this->update($data,"`id_product_attribute` = ". $idProductAttribute);
		}
		
	public function deletePsattribute( $idProductAttribute){
		
		$this->delete("`id_product_attribute` = ". $idProductAttribute);
		
		}	
	
	public function listAll(){
		
		$rows =$this->fetchAll("1","id_product_attribute DESC ");
		if(!$rows) return false;
		return $rows->toArray();			
		
		}
	public function getByReference($ref){
		$row = $this->fetchRow("`reference` LIKE '{$ref}'");
		if(!$row) return false;
		return $row->toArray();		
		
	}		
}


?>