<?php



/**
 * 
 * @author
 * @link http://www.leadcasket.com/zend-model-generator/gen.php
 * ******************************************************************************
 * Please do not remove this block 
 * This class is generated by one page zend db table generator
 * ******************************************************************************
 *
 */

class Model_DbTable_Psimage extends Zend_Db_Table_Abstract {

	protected $_name = 'ps_product_attribute_image';
	
	public function getPsimage( $idProductAttribute){
		
		$row = $this->fetchRow("`id_product_attribute` = ". $idProductAttribute);
		if(!$row) return false;
		return $row->toArray();		
		
		}
		
	public function addPsimage( $idImage){
		
		$data = array(
			
         "id_image" =>  $idImage 
	
			);
		$this->insert($data);
		
		}
		
	public function updatePsimage(  $idProductAttribute ,  $idImage){
		$data = array(
			
         "id_image" =>  $idImage 
	
			);
			
		$this->update($data,"`id_product_attribute` = ". $idProductAttribute);
		}
		
	public function deletePsimage( $idProductAttribute){
		
		$this->delete("`id_product_attribute` = ". $idProductAttribute);
		
		}	
	
	public function listAll(){
		
		$rows =$this->fetchAll("1","id_product_attribute DESC ");
		if(!$rows) return false;
		return $rows->toArray();			
		
		}	
}


?>