<?php



/**
 * 
 * @author
 * @link http://www.leadcasket.com/zend-model-generator/gen.php
 * ******************************************************************************
 * Please do not remove this block 
 * This class is generated by one page zend db table generator
 * ******************************************************************************
 *
 */

class Model_DbTable_Psproduct extends Zend_Db_Table_Abstract {

	protected $_name = 'ps_product_lang';
	
	public function getPsproduct( $idProduct){
		
		$row = $this->fetchRow("`id_product` = ". $idProduct);
		if(!$row) return false;
		return $row->toArray();		
		
		}
		
	public function addPsproduct( $idSupplier , $idManufacturer , $idTaxRulesGroup , $idCategoryDefault , $idColorDefault , $onSale , $onlineOnly , $ean13 , $upc , $ecotax , $quantity , $minimalQuantity , $price , $wholesalePrice , $unity , $unitPriceRatio , $additionalShippingCost , $reference , $supplierReference , $location , $width , $height , $depth , $weight , $outOfStock , $quantityDiscount , $customizable , $uploadableFiles , $textFields , $active , $availableForOrder , $condition , $showPrice , $indexed , $cacheIsPack , $cacheHasAttachments , $cacheDefaultAttribute , $dateAdd , $dateUpd){
		
		$data = array(
			
         "id_supplier" =>  $idSupplier ,
         "id_manufacturer" =>  $idManufacturer ,
         "id_tax_rules_group" =>  $idTaxRulesGroup ,
         "id_category_default" =>  $idCategoryDefault ,
         "id_color_default" =>  $idColorDefault ,
         "on_sale" =>  $onSale ,
         "online_only" =>  $onlineOnly ,
         "ean13" =>  $ean13 ,
         "upc" =>  $upc ,
         "ecotax" =>  $ecotax ,
         "quantity" =>  $quantity ,
         "minimal_quantity" =>  $minimalQuantity ,
         "price" =>  $price ,
         "wholesale_price" =>  $wholesalePrice ,
         "unity" =>  $unity ,
         "unit_price_ratio" =>  $unitPriceRatio ,
         "additional_shipping_cost" =>  $additionalShippingCost ,
         "reference" =>  $reference ,
         "supplier_reference" =>  $supplierReference ,
         "location" =>  $location ,
         "width" =>  $width ,
         "height" =>  $height ,
         "depth" =>  $depth ,
         "weight" =>  $weight ,
         "out_of_stock" =>  $outOfStock ,
         "quantity_discount" =>  $quantityDiscount ,
         "customizable" =>  $customizable ,
         "uploadable_files" =>  $uploadableFiles ,
         "text_fields" =>  $textFields ,
         "active" =>  $active ,
         "available_for_order" =>  $availableForOrder ,
         "condition" =>  $condition ,
         "show_price" =>  $showPrice ,
         "indexed" =>  $indexed ,
         "cache_is_pack" =>  $cacheIsPack ,
         "cache_has_attachments" =>  $cacheHasAttachments ,
         "cache_default_attribute" =>  $cacheDefaultAttribute ,
         "date_add" =>  $dateAdd ,
         "date_upd" =>  $dateUpd 
	
			);
		$this->insert($data);
		
		}
		
	public function updatePsproduct(  $idProduct ,  $idSupplier , $idManufacturer , $idTaxRulesGroup , $idCategoryDefault , $idColorDefault , $onSale , $onlineOnly , $ean13 , $upc , $ecotax , $quantity , $minimalQuantity , $price , $wholesalePrice , $unity , $unitPriceRatio , $additionalShippingCost , $reference , $supplierReference , $location , $width , $height , $depth , $weight , $outOfStock , $quantityDiscount , $customizable , $uploadableFiles , $textFields , $active , $availableForOrder , $condition , $showPrice , $indexed , $cacheIsPack , $cacheHasAttachments , $cacheDefaultAttribute , $dateAdd , $dateUpd){
		$data = array(
			
         "id_supplier" =>  $idSupplier ,
         "id_manufacturer" =>  $idManufacturer ,
         "id_tax_rules_group" =>  $idTaxRulesGroup ,
         "id_category_default" =>  $idCategoryDefault ,
         "id_color_default" =>  $idColorDefault ,
         "on_sale" =>  $onSale ,
         "online_only" =>  $onlineOnly ,
         "ean13" =>  $ean13 ,
         "upc" =>  $upc ,
         "ecotax" =>  $ecotax ,
         "quantity" =>  $quantity ,
         "minimal_quantity" =>  $minimalQuantity ,
         "price" =>  $price ,
         "wholesale_price" =>  $wholesalePrice ,
         "unity" =>  $unity ,
         "unit_price_ratio" =>  $unitPriceRatio ,
         "additional_shipping_cost" =>  $additionalShippingCost ,
         "reference" =>  $reference ,
         "supplier_reference" =>  $supplierReference ,
         "location" =>  $location ,
         "width" =>  $width ,
         "height" =>  $height ,
         "depth" =>  $depth ,
         "weight" =>  $weight ,
         "out_of_stock" =>  $outOfStock ,
         "quantity_discount" =>  $quantityDiscount ,
         "customizable" =>  $customizable ,
         "uploadable_files" =>  $uploadableFiles ,
         "text_fields" =>  $textFields ,
         "active" =>  $active ,
         "available_for_order" =>  $availableForOrder ,
         "condition" =>  $condition ,
         "show_price" =>  $showPrice ,
         "indexed" =>  $indexed ,
         "cache_is_pack" =>  $cacheIsPack ,
         "cache_has_attachments" =>  $cacheHasAttachments ,
         "cache_default_attribute" =>  $cacheDefaultAttribute ,
         "date_add" =>  $dateAdd ,
         "date_upd" =>  $dateUpd 
	
			);
			
		$this->update($data,"`id_product` = ". $idProduct);
		}
		
	public function deletePsproduct( $idProduct){
		
		$this->delete("`id_product` = ". $idProduct);
		
		}	
	
	public function listAll(){
		
		$rows =$this->fetchAll("1","id_product DESC ");
		if(!$rows) return false;
		return $rows->toArray();			
		
		}	
}



?>