<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Retrieve Password</title>
</head>
<body style="font:Arial, Helvetica, sans-serif;">

<table width="600" border="0" cellspacing="5" cellpadding="5">
  <form id="form1" name="form1" method="post" action="">
  <tr>
    <td style="width:300px;">Your IP Address:</td>
    <td><input type="text" name="ip_address" id="ip_address" value="<?php echo $_SERVER['REMOTE_ADDR']?>" readonly="readonly" /></td>
  </tr>
  <tr>
    <td>Shop Code</td>
    <td><input type="text" name="shop_code" id="shop_code" value="<?php echo $this->shophead?>" /></td>
  </tr>
  <tr>
    <td>Your Full Name:</td>
    <td><input type="text" name="staff_name" id="staff_name" /></td>
  </tr>
  <tr>
    <td colspan="2" align="center"><input type="submit" name="button" id="button" value="Submit" /></td>
    </tr>
  </form>
</table>
<?php 

if($_POST){
?>
<table width="600" border="0" cellspacing="5" cellpadding="5">
  <tr>
    <td style="text-align:center; font:18px Arial;">Password For Your Store is</td>
  </tr>
  <tr>
    <td style="text-align:center; font:28px Arial;"><?php echo $this->passwords?></td>
  </tr>
</table>
<?php
}
?>
</body>
</html>
