<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<script type="text/JavaScript">
 
function confirmDelete(){
var agree = confirm("Are you sure you want to delete this file?");
if(agree)
     return true;
else
     return false;
}
</script>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
Announce<br />
<table width="700" border="1" cellspacing="0" cellpadding="5">
  <tr>
    <th scope="col" width="150">Date</th>
    <th scope="col">Title</th>
    <th scope="col" width="150">Action</th>
  </tr>
<?php 
foreach($this->nList1 as $key => $v){
?>  
  <tr>
    <td><?=$v['date_news']?></td>
    <td><?=$v['title_news']?></td>
    <td><a href="/companydocs/delete-news?id=<?=$v['id']?>&token=WAXN6BE79H4E" onclick="return confirmDelete()" target="_blank">Delete News</a></td>
  </tr>
<?php }

?>  
</table>

<br />
Product Information<br />
<table width="700" border="1" cellspacing="0" cellpadding="5">
  <tr>
    <th scope="col" width="150">Date</th>
    <th scope="col">Title</th>
    <th scope="col" width="150">Action</th>
  </tr>
<?php 
foreach($this->nList2 as $key => $v){
?>  
  <tr>
    <td><?=$v['date_news']?></td>
    <td><?=$v['title_news']?></td>
    <td><a href="/companydocs/delete-news?id=<?=$v['id']?>&token=WAXN6BE79H4E" onclick="return confirmDelete()" target="_blank">Delete News</a></td>
  </tr>
<?php }

?>  
</table>
<br />
Promotions
<table width="700" border="1" cellspacing="0" cellpadding="5">
  <tr>
    <th scope="col" width="150">Date</th>
    <th scope="col">Title</th>
    <th scope="col" width="150">Action</th>
  </tr>
<?php 
foreach($this->nList3 as $key => $v){
?>  
  <tr>
    <td><?=$v['date_news']?></td>
    <td><?=$v['title_news']?></td>
    <td><a href="/companydocs/delete-news?id=<?=$v['id']?>&token=WAXN6BE79H4E" onclick="return confirmDelete()" target="_blank">Delete News</a></td>
  </tr>
<?php }

?>  
</table>
</body>
</html>
