<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
Hi ,There are 5 news that you must pay attention to<br />
<br />
<table width="700" border="0" cellspacing="0" cellpadding="5">
 
 <?php foreach($this->arrUNews as $news){?>
  <tr>
    <td><?php echo $news[1]?></td>
  </tr>
 <?php }?> 
 <?php foreach($this->arrUDocs as $doc){?>  
    <tr>
    <td><?php echo $doc[1]?></td>
  </tr>
  <?php }?>  
</table>
</body>
</html>
