<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif; font-size:14px; padding:0px; font-weight:bold;" >
<?php  if($this->totalCount >0){?>
<div style="padding:2px; border:#900 solid 2px; width:400px; text-align:center;">
<a href="/companydocs/news-must-see/pv/highlight/is/<?php echo $this->is?>" style="color:#333" target="_blank">Hi, There Are <span style="color:#F00;"><?php echo $this->totalCount; ?></span> News That You Need Attention To.</a>
<?php }?>
</div>
<br />
</body>
</html>
