<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Index Page</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif" >
<p>Create<br />
  <br />
  1.<a href="/barcode/create-barcode-case" target="_blank">Case BarCode</a><br />
  2.<a href="/barcode/create-barcode-design-case" target="_blank">Design Case And Defender Case BarCode</a><br />
  3.<a href="/barcode/create-barcode-bat" target="_blank">Battery BarCode</a><br />
  4.<a href="/barcode/create-barcode-charger" target="_blank">Charger BarCode</a><br />
  5.<a href="/barcode/create-barcode-datacable" target="_blank">Data Cable BarCode</a><br />
  6.<a href="/barcode/create-barcode-handsfree" target="_blank">Hands Free BarCode</a><br />
  7.<a href="/barcode/create-barcode-holder" target="_blank">Holder BarCode</a><br />
  8.<a href="/barcode/create-barcode-sp">Screen Protector BarCode</a><br />
  9.<a href="/barcode/create-barcode-other">Other BarCode</a><br />
  10.Stylus Pen BaCode<br />
  11.Add Color to Exist BarCode
  <br />
  <br />
  <br />
  Manage<br />
  <br />
  1.<a href="/barcode/manage-manu" target="_blank">Manage Mobile Phone 
    Manufacture</a><br />
  2.<a href="/barcode/manage-model" target="_blank">Manage Mobile Phone Model</a><br />
  3.<a href="/barcode/manage-product-sub-type" target="_blank">Manage Product SubType </a><br />
  4.<a href="/barcode/manage-specialcode" target="_blank">Manage Special Code </a><br />
  <br />
  Summary<br />
  <br />
  1.<a href="/barcode/create-file">Today's Summary and Create File For Download </a><br />
</p>
</body>
</html>
