<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
Manufacture
<br />
<table width="800" border="0" cellspacing="0" cellpadding="5">
<form id="form2" name="form2" method="post" action="">
  <tr>
    <td style="width:100px" >ID</td>
    <td style="width:100px" >CODE</td>
    <td style="width:600px" >Description</td>
  </tr>
 <?php 
 foreach($this->list as $key => $value){
 ?> 
  <tr>
    <td><span style="width:400px">
      <input type="text" name="row[<?php echo $value['id_barcode']?>][id]" id="row[<?php echo $value['id_barcode']?>][id]" style="width:50px;" value="<?php echo $value['id_barcode']?>" />
    </span></td>
    <td><span style="width:400px">
      <input type="text" name="row[<?php echo $value['id_barcode']?>][code]" id="row[<?php echo $value['id_barcode']?>][code]" style="width:100px;"  value="<?php echo $value['code_barcode']?>" />
    </span></td>
    <td><span style="width:400px">
      <input type="text" name="row[<?php echo $value['id_barcode']?>][des]" id="row[<?php echo $value['id_barcode']?>][des]" style="width:350px;"  value="<?php echo $value['des_barcode']?>" />
    </span></td>
  </tr>
 <?php 
 }
 ?> 
  <tr>
    <td colspan="3">
      <input type="submit" name="sub_1" id="sub_1" value="Modify" />
</td>
  </tr>
    </form>  
</table>
<p><br />
  Add New<br />
</p>
<table width="600" border="0" cellspacing="0" cellpadding="10">
<form id="form1" name="form1" method="post" action="">
  <tr>
    <td style="width:200px" >ID: {Add By Your Self}</td>
    <td style="width:400px" ><label for="id_add_manu"></label>
    <input type="text" name="id_add_manu" id="id_add_manu" /></td>
  </tr>
  <tr>
    <td>Code:</td>
    <td><span style="width:400px">
      <input type="text" name="code_add_manu" id="code_add_manu" />
    </span></td>
  </tr>
  <tr>
    <td>Description:</td>
    <td><span style="width:400px">
      <input type="text" name="des_add_manu" id="des_add_manu" style="width:350px;" />
    </span></td>
  </tr>
  <tr>
    <td colspan="2">
      <input type="submit" name="sub_2" id="sub_2" value="Add" />
</td>
  </tr>
  </form>  
</table>
<p>  <br />
</p>
</body>
</html>
