<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>

<style type="text/css">
/* <![CDATA[ */

table, td
{
    border-color: #666;
    border-style: solid;
}
table, th
{
    border-color: #666;
    border-style: solid;
}

table
{
    border-width: 0 0 1px 1px;
    border-spacing: 0;
    border-collapse: collapse;
}
 
td
{
    margin: 0;
    padding: 4px;
    border-width: 1px 1px 0 0;
}
th
{
    margin: 0;
    padding: 4px;
    border-width: 1px 1px 0 0;
}

/* ]]> */
</style>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">

<b>Phone Collection Full Menu</b>
<table width="1200"  cellspacing="1" cellpadding="5">
  <tr>
    <th scope="col">Department</th>
    <th scope="col">ID</th>
    <th scope="col">Server</th>
    <th scope="col" style="width:450px;">Link</th>
    <th scope="col" style="width:200px; font-size:10px;">How-To</th>
    <th scope="col" style="width:200px; font-size:10px;">Comment</th>
    <th scope="col">Date</th>
  </tr>
<?php foreach($this->mList as $key => $v) {?>  
  <tr>
    <td><?php echo $v["department"]?></td>
    <td><?php echo $v["id_menu"]?></td>
    <td><?php echo ($v["id_server"])?"TS(126)": "PS(124)"; ?></td>
    <td><a href="<?php echo $v["link"]?>" target="_blank" ><?php echo $v["link_text"]?></a></td>
    <td style="width:200px; font-size:10px;"><?php echo $v["useage"]?></td>
    <td style="width:200px; font-size:10px;"><?php echo $v["comment"]?></td>
    <td><?php echo $v["last_change"]?></td>
  </tr>
<?php }?>  
</table>



</body>
</html>
