<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<META name="robots" content="NOINDEX,NOFOLLOW" />
<META name="googlebot" content="NOARCHIVE, NOODP, NOSNIPPET" />

<title>Untitled Document</title>
</head>
<body>
<table width="300" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td>
    <img src="http://www.phonecollection.com.au/images/logo_phonecollection.png" />
    
    <br />

    Phone Collection Internal Application V 1.0 
    </td>
  </tr>
</table>
</body>
</html>
