<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Online RMA Lodgement System</title>
<link href="/css/template.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="600" border="0" cellspacing="0" cellpadding="10" align="center">
<form id="form_step0" name="formstep0" method="post" action="/rma/fill">
  <tr>
    <td><a title="Phone Collection" href="http://www.newgenerationgroup.com.au/index.php"> <img id="logo" src="http://www.newgenerationgroup.com.au/images/logo-phone-collection.png" alt="Phone Collection" border="0" /></a></td>
  </tr>
  <tr>
    <td class="theh1" >Phone Collection Online RMA Lodgement System <br />
    <h3>Please Access your RMA system using Your company Information Page<br />
   	</h3>   
 
    <br /></td>
  </tr>
 <!-- 
  <tr>
    <td align="left" valign="middle"><span style="font-weight:bold;">IN VICTORIA</span></td>
  </tr>
  <tr>
    <td align="center" valign="middle"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td style="width:200px;"><span class="theh1" >Phone Collection</span></td>
        <td style="line-height:30px; text-transform:capitalize;"><a href="/rma/new/shop/BSPC" >Bayside Phone Collection</a><br />
          <a href="/rma/new/shop/BHPC">Boxhill Phone Collection</a><br />
          <a href="/rma/new/shop/BBPC">Brimbank Phone Collection</a><br />
          <a href="/rma/new/shop/COPC">Corio Phone Collection</a><br />
          <a href="/rma/new/shop/CBPC">Cranbourne Phone Collection</a><br />
          <a href="/rma/new/shop/EPPC">Epping Phone Collection</a><br />
          <a href="/rma/new/shop/FGPC">Fountain Gate Phone Collection</a><br />
          <!--<a href="/rma/new/shop/HPPC">High Point Phone Collection</a><br />
          <a href="/rma/new/shop/KCPC">Knox City Phone Collection</a><br />
          <a href="/rma/new/shop/NLPC">Northland Phone Collection</a><br />
          <a href="/rma/new/shop/PMPC">Parkmore Phone Collection</a><br />
          <a href="/rma/new/shop/WBPC">Werribee Phone Collection</a><br />
          <a href="/rma/new/shop/WGPC">WaterGarden Phone Collection</a><br />
           <br />       
          </td>
      </tr>
      <tr>
        <td style="width:200px;" ><span class="theh1" >iCollection</span></td>
        <td  style="line-height:30px; text-transform:capitalize;"><a href="/rma/new/shop/BSIC">Bayside iCollection</a><br />
          <a href="/rma/new/shop/SLIC">Southland iCollection</a><br />
          <a href="/rma/new/shop/WGIC">Water Garden iCollection</a><br />
          <a href="/rma/new/shop/WBIC">Werribee iCollection</a><br />    
          <a href="/rma/new/shop/CSIC">Chadstone ICollection</a>*<br />
          <a href="/rma/new/shop/DCIC">Doncaster ICollection</a>*<br />
          <a href="/rma/new/shop/PMIC">Parkmore ICollection</a>*<br />
          <a href="/rma/new/shop/BSXP">Bayside Xpress  Repair</a>*<br />
          <a href="/rma/new/shop/FGIC">Foutain Gate ICollection</a>*<br />
          </td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td align="left" valign="middle"><span style="font-weight:bold;" >IN SOUTH AUSTRALIA</span></td>
  </tr>
  <tr>
    <td align="center" valign="middle"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><a href="/rma/new/shop/ADPC">Arndale Phone Collection</a></td>
        <td><a href="/rma/new/shop/CLPC">Colonnades Phone Collection<br />
          <br />
        </a>
        <a href="/rma/new/shop/CLIC">Colonnades ICollection</a><br />
        
        </td>
        <td><a href="/rma/new/shop/WLIC">West Lake iCollection</a></td>
      </tr>
    </table></td>
  </tr>
  -->
  <tr>
    <td><p>Copyright &copy; Phone Collection 2012<br />
    *This form is designed for internal use only<br />
    *Your IP address: recorderd as evidence<br />
    *Do not use this form in any other circumstances , only use this form on the store computer<br />
    *Should you have any problem , please call head office ASAP!</p>
    <p>&nbsp;</p></td>
  </tr>
</form> 
</table>
</body>
</html>
