<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
<h1>Check Your Shop's Roster Online</h1>
* Click Links Below to Check The Online Roster For Different Period<br />
* You Actual Hours May Vary After the Manager Modification<br />
* The Total Hours Here May or May not include the correct break time<br />
<br />
Check <a href="/roster/online-roster-last-week/shop/<?php echo $this->shop ?>" target="_blank">Last Week Roster</a> |  <a href="/roster/online-roster-this-week/shop/<?php echo $this->shop ?>">Current Week Roster</a> | <a href="/roster/online-roster-next-week/shop/<?php echo $this->shop ?>">Next Week Roster</a><br />
</body>
</html>
