<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif">
<h1>Input Your Staff's Detail</h1>
<form id="form1" name="form1" method="post" action="">
  <table width="500" border="0" cellspacing="0" cellpadding="10" align="center">
   <tr>
      <td>Formal First Name<br />
      (Space WIll be Omit)</td>
      <td><input name="first_name" type="text" id="first_name" size="50" /></td>
    </tr>
    <tr>
      <td>Formal Last Name</td>
      <td><input name="last_name" type="text" id="last_name" size="50" /></td>
    </tr>
    <tr>
      <td>Nick Name<br />
      English Name</td>
      <td><input name="nick_name" type="text" id="nick_name" size="50" /></td>
    </tr>
    <tr>
      <td>Date of Birth</td>
      <td><select name="day" id="day">
          <option value="01">01</option>
          <option value="02">02</option>
          <option value="03">03</option>
          <option value="04">04</option>
          <option value="05">05</option>
          <option value="06">06</option>
          <option value="07">07</option>
          <option value="08">08</option>
          <option value="09">09</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
          <option value="13">13</option>
          <option value="14">14</option>
          <option value="15">15</option>
          <option value="16">16</option>
          <option value="17">17</option>
          <option value="18">18</option>
          <option value="19">19</option>
          <option value="20">20</option>
          <option value="21">21</option>
          <option value="22">22</option>
          <option value="23">23</option>
          <option value="24">24</option>
          <option value="25">25</option>
          <option value="26">26</option>
          <option value="27">27</option>
          <option value="28">28</option>
          <option value="29">29</option>
          <option value="30">30</option>
          <option value="31">31</option>
        </select>
        /
        <select name="month" id="month">
          <option value="01">Jan.</option>
          <option value="02">Feb.</option>
          <option value="03">Mar.</option>
          <option value="04">Apr.</option>
          <option value="05">May</option>
          <option value="06">June</option>
          <option value="07">July</option>
          <option value="08">Aug.</option>
          <option value="09">Sept.</option>
          <option value="10">Oct.</option>
          <option value="11">Nov.</option>
          <option value="12">Dec.</option>
        </select>
        /
        <select name="year" id="year">
          <option value="1970">1970</option>
          <option value="1971">1971</option>
          <option value="1972">1972</option>
          <option value="1973">1973</option>
          <option value="1974">1974</option>
          <option value="1975">1975</option>
          <option value="1976">1976</option>
          <option value="1977">1977</option>
          <option value="1978">1978</option>
          <option value="1979">1979</option>
          <option value="1980">1980</option>
          <option value="1981">1981</option>
          <option value="1982">1982</option>
          <option value="1983">1983</option>
          <option value="1984">1984</option>
          <option value="1985">1985</option>
          <option value="1986">1986</option>
          <option value="1987">1987</option>
          <option value="1988">1988</option>
          <option value="1989">1989</option>
          <option value="1990">1990</option>
          <option value="1991">1991</option>
          <option value="1992">1992</option>
          <option value="1993">1993</option>
          <option value="1994">1994</option>
          <option value="1995">1995</option>
          <option value="1996">1996</option>
          <option value="1997">1997</option>
          <option value="1998">1998</option>
          <option value="1999">1999</option>          <option value="2000">2000</option>          
        </select></td>
    </tr>
    <tr>
      <td colspan="2" align="center"><input type="submit" name="btn_setup_password" id="btn_setup_password" value="SAVE"  disabled="disabled" />
        <br />
        <br />
        DO NOT USE THIS FUNCTION ANYMORE, USING NEW STAFF REGISTER FUNCTION IN THE CIP<br />
      <br />
     <?php echo $this->message;?>
     </td>
    </tr>
  
    <tr>
      <td colspan="2" bgcolor="#D6FEE6" style="font-size: 13px;"><p>Welcome,please input your Staff Detail so they will able to setup</p>
        <p>++++++++++++++++++++++++++++++++++++++++++++++++++<br />
          <h3>READ CAREFULLY ---------&gt; RULES TO FOLLOW</h3>
          ++++++++++++++++++++++++++++++++++++++++++++++++++
<br />
          <br />
          1) Use The &quot;Formal&quot; Name which on the Passport Or Driver Licience, eg: My Name is Qian qiao Dong, My Nick Name is Norman<br />
          Use &quot;Qianqiao&quot; , do NOT use Norman
          <br />
          <br />
          2) If there were a middle name, put together in the &quot;First Name&quot;<br />
          <br />
          3)You may use Upper Case and Space during the input , but all will change to &quot;lower&quot; case and space will be &quot;omit&quot; , this is normal , eg:<br />
        If input my name is  Qian Qiao , Last name is Dong , it will be change to  : qianqiao dong<br />
        <br />
        4)If you made Mistakes, Record the (wrong name, wrong DOB)
        , do the correct one once again , when you finish all your staffs , email me the wrong one , I will delete/edit them.<br />
        <br />
        5) Highly unlikely, we will met EXACTLY same name, 
        same DOB person, may be from different shop, if you see &quot;record Already Exist&quot; and you 100% sure you never input this staff before , let me know</p></td>
    </tr>
   
  </table>
</form>
</body>
</html>
