<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif;" background="/im/C-Horse1-2014A.png">
<?php
if(!$this->errorFlag){
?>
<form id="form1" name="form1" method="post" action="">
<table width="650" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td>Login Please</td>
  </tr>
  <tr>
    <td align="center"><br />
      <input name="password" type="password" id="password" size="50" />
      <br />
    <br /></td>
  </tr>
  <tr>
    <td align="center"><input type="submit" name="button" id="button" value="Login to Change Status" />
      <br />
      <br />
      <a href="/cpInfo/hp_<?=$this->shopHead?>.php#c">Return to Company Information Page</a>
      </td>
  </tr>
</table>
</form>
<?php

}
if($this->errorFlag || $this->errorFlag2){
?><br />

<table width="500" border="0" cellspacing="0" cellpadding="10" align="center" style="border:#603 1px solid;">
  <tr>
    <td align="center" bgcolor="#FEDADD"><?=$this->errorMessage ?></td>
  </tr>
</table>
<?php 
}
?>
</body>
</html>
