<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
<h2>Shift Hour Auditing  On 2013-04-16,By :_________</h2>
<form id="form1" name="form1" method="post" action="">
  <table width="100%" border="0" cellspacing="1" cellpadding="10" bgcolor="#000000">
    <tr>
      <th bgcolor="#FFFFFF" scope="col">DOW<br />
        (Day of Week)</th>
      <th colspan="4" bgcolor="#FFFFFF" scope="col">Monday<br />
      (2013-04-08)</th>
      <th rowspan="2" bgcolor="#FFFFFF" scope="col">Tuesday<br />
      (2013-04-08)</th>
      <th rowspan="2" bgcolor="#FFFFFF" scope="col">Wednesday<br />
      (2013-04-08)</th>
      <th rowspan="2" bgcolor="#FFFFFF" scope="col">Thursday<br />
      (2013-04-08)</th>
      <th rowspan="2" bgcolor="#FFFFFF" scope="col">Friday<br />
      (2013-04-08)</th>
      <th rowspan="2" bgcolor="#FFFFFF" scope="col">Saturday<br />
      (2013-04-08)</th>
      <th rowspan="2" bgcolor="#FFFFFF" scope="col">Sunday<br />
      (2013-04-08)</th>
    </tr>
    <tr>
      <th bgcolor="#FFFFFF" scope="col">Shop Name</th>
      <th bgcolor="#FFFFFF" scope="col">Staff</th>
      <th bgcolor="#FFFFFF" scope="col">Begin</th>
      <th bgcolor="#FFFFFF" scope="col">End</th>
      <th bgcolor="#FFFFFF" scope="col">Action</th>
    </tr>
    <tr>
      <td rowspan="2" bgcolor="#FFFFFF">BSPC</td>
      <td bgcolor="#FFFFFF">Adele</td>
      <td bgcolor="#FFFFFF"><label for="select"></label>
        <select name="select" id="select">
      </select>
        :        
        <select name="select2" id="select2">
        </select></td>
      <td bgcolor="#FFFFFF"><select name="select3" id="select3">
      </select>
:
<select name="select4" id="select4">
</select></td>
      <td bgcolor="#FFFFFF"><input type="checkbox" name="checkbox" id="checkbox" />
        Confirm</td>
      <td rowspan="2" bgcolor="#FFFFFF">`</td>
      <td rowspan="2" bgcolor="#FFFFFF">&nbsp;</td>
      <td rowspan="2" bgcolor="#FFFFFF">&nbsp;</td>
      <td rowspan="2" bgcolor="#FFFFFF">&nbsp;</td>
      <td rowspan="2" bgcolor="#FFFFFF">&nbsp;</td>
      <td rowspan="2" bgcolor="#FFFFFF">&nbsp;</td>
    </tr>
    <tr>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
    </tr>
    <tr>
      <td bgcolor="#FFFFFF">BSIC</td>
      <td colspan="4" bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
    </tr>
    <tr>
      <td bgcolor="#FFFFFF">BSXP</td>
      <td colspan="4" bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
      <td bgcolor="#FFFFFF">&nbsp;</td>
    </tr>
  </table>
</form>
</body>
</html>
