<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body style="font-family:Tahoma, Geneva, sans-serif">
<h1>Thanks For the Information<br />
  An Welcome Letter Has Been Send To You<br />
</h1>
<p>Please follow
  instructions in the welcome letter to provide necessary documents as requested.<br />
</p>
<p><h1>Now You May Begin To Setup Your Own Password.</h1>
  <br />
  <a href="/roster/setup" target="_blank">Click Here To Setup The Password</a>
</p>
<p>&nbsp;</p>
</body>
</html>
