<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<p>Super User Time Sheet has been Added</p>
<p>There is no turnning back</p>
<p>if any mistake , ask Norman to remove it</p>
<p>you may close the window now </p>
<p>you should F5 the online roster page you can see the result</p>
<p>&nbsp;</p>
</body>
</html>
