<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
<table width="650" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td style="border:1px #C00 solid; background-color:#FB9FBB; text-align:center;">
	<?php
echo $this->errorMessage;
?></td>
  </tr>
  <tr>
    <td style="border:1px #060 solid; background-color:#B9FFB9;text-align:center;"><?php
echo $this->goodNews;
?></td>


  </tr>
  <tr>
    <td style="border:1px #060 solid; background-color:#B9FFB9;text-align:center;"><a href="/cpInfo/hp_<?=$this->realshopHead?>.php">Click to Return Home Page</a></td>


  </tr>  
</table>
</body>
</html>
