<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
 
$(document).ready(function(){
 
        $(".slidingDiv").hide();
        $(".show_hide").show();
 
    $('.show_hide').click(function(){
    $(".slidingDiv").slideToggle();
    });
 
});
 
</script>
<style type="text/css" >

.slidingDiv {
    height:30px;
	width:100%;
    background-color: #99CCFF;
    padding:5px;
    margin-top:5px;
    border-bottom:2px solid #3399FF;
}
 
.show_hide {
    display:none;
}



</style>

</head>
<body style="font-family:Arial, Helvetica, sans-serif">
<h1>Setup your login password</h1>
<?php
//var_dump($this->ifMobile);
if(!$this->ifMobile){
?>
<form id="form1" name="form1" method="post" action="">
<?php
if($this->showFirst){
?>
  <table width="500" border="0" cellspacing="0" cellpadding="10" align="center">
    <tr>
      <td colspan="2" bgcolor="#D6FEE6">Welcome, please input your name and date of birth to proof your identity</td>
    </tr>
    <tr>
      <td>Formal Given Name</td>
      <td><input name="first_name" type="text" id="first_name" size="30" /></td>
    </tr>
    <tr>
      <td>Formal Surname</td>
      <td><input name="last_name" type="text" id="last_name" size="30" /></td>
    </tr>
    <tr>
      <td>Date of Birth</td>
      <td><select name="day" id="day">
          <option value="01">01</option>
          <option value="02">02</option>
          <option value="03">03</option>
          <option value="04">04</option>
          <option value="05">05</option>
          <option value="06">06</option>
          <option value="07">07</option>
          <option value="08">08</option>
          <option value="09">09</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>
          <option value="13">13</option>
          <option value="14">14</option>
          <option value="15">15</option>
          <option value="16">16</option>
          <option value="17">17</option>
          <option value="18">18</option>
          <option value="19">19</option>
          <option value="20">20</option>
          <option value="21">21</option>
          <option value="22">22</option>
          <option value="23">23</option>
          <option value="24">24</option>
          <option value="25">25</option>
          <option value="26">26</option>
          <option value="27">27</option>
          <option value="28">28</option>
          <option value="29">29</option>
          <option value="30">30</option>
          <option value="31">31</option>
        </select>
        /
        <select name="month" id="month">
          <option value="01">Jan.</option>
          <option value="02">Feb.</option>
          <option value="03">Mar.</option>
          <option value="04">Apr.</option>
          <option value="05">May</option>
          <option value="06">June</option>
          <option value="07">July</option>
          <option value="08">Aug.</option>
          <option value="09">Sept.</option>
          <option value="10">Oct.</option>
          <option value="11">Nov.</option>
          <option value="12">Dec.</option>
        </select>
        /        
        <label for="year"></label>
        <input type="text" name="year" id="year" /></td>
    </tr>
    <tr>
      <td colspan="2" align="center"><input type="submit" name="btn_setup_password" id="btn_setup_password" value="Setup My Password" /></td>
    </tr>
  </table>
  <br />
<br />
<?php
}
if($this->showSecond){
?>
  <table width="500" border="0" cellspacing="0" cellpadding="10" align="center">
    <tr>
      <td colspan="2" bgcolor="#D6FEE6"><?=$this->fullName?> Welcome , Now Setting Up your Password
        <input name="user_id" type="hidden" id="user_id" value="<?=$this->userID?>" />
      <input name="password_aftercheck" type="hidden" id="password_aftercheck" value="<?=$this->passwordAftercheck?>" /></td>
    </tr>
<?php
if(!$this->passwordChecked){
?>    
    <tr>
      <td colspan="2">* Password should be  8 to15 charactors<br />
* Include only letters and numbers<br />
* Symbols and marks are not recommanded<br />
*
      Contain at least one number, one Upper and one Lower case </td>
    </tr>
    <tr>
      <td>Password</td>
      <td><input name="password" type="password" id="password" size="15" style="width:150px;" /></td>
    </tr>
    <tr>
      <td>Confirm Password</td>
      <td><input name="password_confirm" type="password" id="password_confirm" size="15" style="width:150px;" /></td>
    </tr>
<?php
}
 if($this->passwordChecked){
 ?>    
    <tr>
      <td>Your Password:<br />
        <span style="font-size:12px;">Check password again before save it</span></td>
      <td align="left">
      <a href="#" class="show_hide">Show / Hide</a><br />
<div class="slidingDiv">
<?=$this->passwordAftercheck?>
</div>

      </td>
    </tr>
<?php
 }
?>    
    <tr>
      <td colspan="2" align="center">
 <?php
 if($this->passwordChecked){
 ?>     
      <input type="submit" name="btn_record_password" id="btn_record_password" value="Password Checked, Now Save It" style="color:#060;" />
<?php
 }
 else{
?>    
      <input type="submit" name="btn_check_password" id="btn_check_password" value="Check My Password" style="color:#C30;" />
<?php }?>
        
      </td>
    </tr>
  </table>
  <br />
  <br />
<?php
}
?>  
</form>
<?php
}

?>
<?php
if($this->errorFlag){
?>
<table width="500" border="0" cellspacing="0" cellpadding="10" align="center" style="border:#603 1px solid;">
  <tr>
    <td align="center" bgcolor="#FEDADD"><?=$this->errorMessage?></td>
  </tr>
</table>
<?php
}
?>
</body>
</html>
