<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
<table width="500" border="0" cellspacing="0" cellpadding="10" align="center">
  <tr>
    <td align="center" style="border:#070 1px solid; background-color:#C6FCC5 "><p>Thanks , The setup now is done <br />
      <br />
    please download the <a href="/docs/staffattendancetutorial.doc" target="_blank">tutorial</a> here for the login in our company information page </p>
    <p>You may close the window now</p></td>
  </tr>
</table>
</body>
</html>
