<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
/* <![CDATA[ */

table, td
{
    border-color: #666;
    border-style: solid;
}
table, th
{
    border-color: #666;
    border-style: solid;
}

table
{
    border-width: 0 0 1px 1px;
    border-spacing: 0;
    border-collapse: collapse;
}

td
{
    margin: 0;
    padding: 8px;
    border-width: 1px 1px 0 0;
}
th
{
    margin: 0;
    padding: 8px;
    border-width: 1px 1px 0 0;
}

/* ]]> */
</style>

</head>

<body style="font-family:Arial, Helvetica, sans-serif">
<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
<table width="600" border="0" cellspacing="0" cellpadding="10">
  <tr>
    <td colspan="2"><h1 style="color:#069">Upload Photo ID</h1></td>
  </tr>
  <tr>
    <td colspan="2">
      <label for="email_addr">Why we need your Photo ID:<br />
        <br />
        What Type Of ID We Will Accept:<br />
        <br />
        What Type Of ID We Will Not Accept:<br />
        <br />
        Size Limits on the ID File:
<br />
        <br />
        <br />
      </label></td>
    </tr>
  <tr>
    <td>You Photo ID File:</td>
    <td><label for="fileField"></label>
      <input type="file" name="fileField" id="fileField" />
      <span style="font-size:12px;"><i> (max file size:2MB = 2048KB)</i></span></td>
  </tr>
  <tr>
    <td>ID Expire Date</td>
    <td><select name="day" id="day">
      <option value="01">01</option>
      <option value="02">02</option>
      <option value="03">03</option>
      <option value="04">04</option>
      <option value="05">05</option>
      <option value="06">06</option>
      <option value="07">07</option>
      <option value="08">08</option>
      <option value="09">09</option>
      <option value="10">10</option>
      <option value="11">11</option>
      <option value="12">12</option>
      <option value="13">13</option>
      <option value="14">14</option>
      <option value="15">15</option>
      <option value="16">16</option>
      <option value="17">17</option>
      <option value="18">18</option>
      <option value="19">19</option>
      <option value="20">20</option>
      <option value="21">21</option>
      <option value="22">22</option>
      <option value="23">23</option>
      <option value="24">24</option>
      <option value="25">25</option>
      <option value="26">26</option>
      <option value="27">27</option>
      <option value="28">28</option>
      <option value="29">29</option>
      <option value="30">30</option>
      <option value="31">31</option>
    </select>
/
<select name="month" id="month">
  <option value="01">Jan.</option>
  <option value="02">Feb.</option>
  <option value="03">Mar.</option>
  <option value="04">Apr.</option>
  <option value="05">May</option>
  <option value="06">June</option>
  <option value="07">July</option>
  <option value="08">Aug.</option>
  <option value="09">Sept.</option>
  <option value="10">Oct.</option>
  <option value="11">Nov.</option>
  <option value="12">Dec.</option>
</select>
/
<input type="text" name="year" id="year" style="width:50px;" />
<span style="font-size:12px;"><i> (yyyy e.g. 2014)</i></span></td>
  </tr>
  <tr>
    <td colspan="2" align="center"><br />
      <br /><input type="submit" name="btn_submit" id="btn_submit" value="Proceed &gt; &gt;" /></td>
  </tr>
</table>
 </form>
</body>
</html>
