<?php
/**
 * 
 * @author Norman Dong
 * @link http://www.leadcasket.com/zend-model-generator/gen.php
 * ******************************************************************************
 * Please do not remove this block 
 * This class is generated by one page zend db table generator
 * ******************************************************************************
 * Company Document Access Log Class
 * Company Document Include Company News And Company Documents
 * Both has Field Called Must see
 * For Must See Docs/ News , Record If the Guy Already See it Or Not 
 * Start On 02/01/14
 */

class Model_Message_Cdocacclog extends Zend_Db_Table_Abstract {

	protected $_name = 'company_news_access_log';
	
	public function getCdocacclog( $idLog){
		
		$row = $this->fetchRow("`id_log` = ". $idLog);
		if(!$row) return false;
		return $row->toArray();		
		
		}
		
	public function addCdocacclog( $idNews , $idDoc , $idStaff , $dateView , $timeView){
		
		$data = array(
			
         "id_news" =>  $idNews ,
         "id_doc" =>  $idDoc ,
         "id_staff" =>  $idStaff ,
         "date_view" =>  $dateView ,
         "time_view" =>  $timeView 
	
			);
		$this->insert($data);
		
		}
		
	public function updateCdocacclog(  $idLog ,  $idNews , $idDoc , $idStaff , $dateView , $timeView){
		$data = array(
			
         "id_news" =>  $idNews ,
         "id_doc" =>  $idDoc ,
         "id_staff" =>  $idStaff ,
         "date_view" =>  $dateView ,
         "time_view" =>  $timeView 
	
			);
			
		$this->update($data,"`id_log` = ". $idLog);
		}
		
	public function deleteCdocacclog( $idLog){
		
		$this->delete("`id_log` = ". $idLog);
		
		}	
	
	public function listAll(){
		
		$rows =$this->fetchAll("1","id_log DESC ");
		if(!$rows) return false;
		return $rows->toArray();			
		
		}	
	public function ifNewsRead($idNews,$idStaff){
		
		$whereStr = "`id_news` = {$idNews} AND `id_staff` = {$idStaff}";
		$row = $this->fetchRow($whereStr);
		if(!$row) return false;
		return $row->toArray();
		
	}	
	public function ifDocOpened($idDoc,$idStaff){
		// only news will record time 
		
		$whereStr = "`id_doc` = {$idDoc} AND `id_staff` = {$idStaff}";
		$row = $this->fetchRow($whereStr);
		if(!$row) return false;
		return $row->toArray();
		
	}	
}


?>