<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
<h1>Hour Limits <br />
</h1>
<form action="" method="post">
<table width="600" border="1" cellspacing="0" cellpadding="10">
  <tr>
    <th scope="col">Shop</th>
    <th scope="col">Limits</th>
  </tr>
  <?php foreach($this->sList as $key => $v){ ?>
  <tr>
    <td><?php echo $v['name_shop_location_head'];?></td>
    <td><input name="hour_limits[<?php echo $v['name_shop_location_head'];?>]" type="text" value="<?php echo $v['hour_limit'];?>" /></td>
  </tr>
  <?php } ?>
</table>
<input name="submit" type="submit" />
</form>

</body>
</html>
