<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
/* <![CDATA[ */

table, td
{
    border-color: #666;
    border-style: solid;
}
table, th
{
    border-color: #666;
    border-style: solid;
}

table
{
    border-width: 0 0 1px 1px;
    border-spacing: 0;
    border-collapse: collapse;
}

td
{
    margin: 0;
    padding: 8px;
    border-width: 1px 1px 0 0;
}
th
{
    margin: 0;
    padding: 8px;
    border-width: 1px 1px 0 0;
}

/* ]]> */
</style>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
<h1>Online Product Finder Of <?php echo $this->shop?></h1>
<h2>
Scan Or Type In Barcode Here:</h2>

<form id="form1" name="form1" method="post" action="">

<input name="bar_code" type="text" id="bar_code" width="300" style="font-size:20px;" />
  <input type="submit" name="button" id="button" value="Search"  style="font-size:20px;" />
</form>

