<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Phone Collection Product Database</title>
</head>

<body>
<table width="800" border="1" cellspacing="5" cellpadding="5">
  <tr>
    <td><h1>E-Commerce Department Function</h1></td>
  </tr>
  <tr>
    <td><p><a href="/products/warehouse-in">Warehouse Transfer IN</a> | <a href="/products/print-warehouse-in">Print All Transfer In Today</a> | <a href="/products/warehouse-out">Warehouse Transfer OUT</a> |</p>
      <p> <a href="/products/goods-in">Purchase Products</a> | Stock Taking | Error Correction | Match Barcode | <a href="/products/batch-goods-out">Batch Good Out</a> | Error Correction</p>
<p>Purchase Invoice</p></td>
  </tr>
  <tr>
    <td><h1>Warehouse Department Function</h1></td>
  </tr>
  <tr>
    <td><a href="/products/whbatchimport" target="_blank">Import APOS Stock</a> | Setting Up Stock Alert Level | Mach Barcode</td>
  </tr>
  <tr>
    <td><h1>Admin Department Function</h1></td>
  </tr>
  <tr>
    <td><a href="/products/list-products">product list</a> |</td>
  </tr>
  <tr>
    <td><h1>China Department Function</h1></td>
  </tr>
  <tr>
    <td>Add Supplier | Search BarCode | Add Details | Create New Barcodes | </td>
  </tr>
  <tr>
    <td><h1>Config and Managing Function</h1></td>
  </tr>
  <tr>
    <td>Check Missing Pictures | Merge Barcode | </td>
  </tr>  
</table>
</body>
</html>
