<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif; font-size:16px;">
<table width="600" border="0" cellspacing="1" cellpadding="10">
  <tr>
    <th scope="col">OLD APOS</th>
    <th scope="col">NEW APOS</th>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/ADPC" target="_blank" >ADPC</a></td>
    <td><a href="/products/last-week-discount-new/shop/BSXP" target="_blank" >BSXP</a></td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/BBPC" target="_blank" >BBPC</a></td>
    <td><a href="/products/last-week-discount-new/shop/CLIC" target="_blank" >CLIC</a></td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/BHPC" target="_blank" >BHPC</a></td>
    <td><a href="/products/last-week-discount-new/shop/CSIC" target="_blank" >CSIC</a></td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/BSIC"  target="_blank" >BSIC</a></td>
    <td><a href="/products/last-week-discount-new/shop/DCIC"  target="_blank" >DCIC</a></td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/BSPC"  target="_blank" >BSPC</a></td>
    <td><a href="/products/last-week-discount-new/shop/FGIC"  target="_blank" >FGIC</a></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><a href="/products/last-week-discount-new/shop/HPIC" target="_blank" >HPIC</a></td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/CLPC" target="_blank" >CLPC</a></td>
    <td><a href="/products/last-week-discount-new/shop/PMIC" target="_blank" >PMIC</a></td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/EPPC" target="_blank" >EPPC</a></td>
    <td><a href="/products/last-week-discount-new/shop/CBPC" target="_blank" >CBPC</a></td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/KCPC" target="_blank" >KCPC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/NLPC" target="_blank" >NLPC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/PMPC" target="_blank" >PMPC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/SLIC" target="_blank" >SLIC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/WBIC" target="_blank" >WBIC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/WBPC" target="_blank" >WBPC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/WGIC" target="_blank" >WGIC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/WGPC" target="_blank" >WGPC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="/products/last-week-discount-old/shop/WLIC" target="_blank" >WLIC</a></td>
    <td>&nbsp;</td>
  </tr>
</table>

</body>
</html>
