<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body>
<table width="800" border="0" cellspacing="1" cellpadding="5">
  <tr>
    <th scope="col">Item</th>
    <th scope="col">Title</th>
    <th scope="col">Loc</th>
    <th scope="col">Sales</th>
    <th scope="col">Stock</th>
  </tr>
 <?php
foreach($this->arrfinal as $line){
?>	 
  <tr>
    <td><?=$line[0]?></td>
    <td><?=$line[1]?></td>
    <td><?=$line[2]?></td>
    <td><?=$line[3]?></td>
    <td><?=(int)$line[4]?></td>
  </tr>
<?php } ?>
</table>

</body>
</html>
