<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<table width="1000" border="1" cellspacing="0" cellpadding="10">
  <?php
  foreach($this->manuList as $k => $manu){
  ?>
  <tr>
    <td><?php echo $manu['des_barcode']?> &nbsp;</td>
    <?php foreach($this->modelList[$manu['code_barcode']] as $models ){?>
    <td><a href="/products/newsletter-online/manu/<?php echo $models['id_manu_model']?>/model/<?php echo $models['id_model']?>"><?php echo $models['des_model']?></a> &nbsp;</td>
    <?php }?>
    
  </tr>
  <?php  } ?>
</table>
</body>
</html>
