<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
/* <![CDATA[ */
table, td
{
    border-color: #666;
    border-style: solid;
}
table, th
{
    border-color: #666;
    border-style: solid;
}

table
{
    border-width: 0 0 1px 1px;
    border-spacing: 0;
    border-collapse: collapse;
}
 
td
{
    margin: 0;
    padding: 4px;
    border-width: 1px 1px 0 0;
}
th
{
    margin: 0;
    padding: 4px;
    border-width: 1px 1px 0 0;
}
/* ]]> */


</style>

</head>
<body style="font-family:Arial, Helvetica, sans-serif">

<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
  <p>ODNO .: 
    <label for="no_od"></label>
    <label for="upload"></label>
    <input type="file" name="upload" id="upload" />
  </p>
  <p><br />
    KTNO.:
    <input type="text" name="no_kt" id="no_kt" />
  </p>
  <p>SHOP.: 
    <input type="text" name="shop" id="shop" />
  </p>
  <p>
    <input type="submit" name="button" id="button" value="Submit" />
  </p>
</form>
<?php
if($_POST){
?>
<h1>Extra Product Sent</h1>
<table width="700" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td>Barcode</td>
    <td>Description</td>
    <td>Should</td>
    <td>Actual</td>
  </tr>
  
<?php 
if(!empty($this->arrResExtra)){
foreach($this->arrResExtra as $k1 => $v1) {?>  
  <tr>
    <td><?php echo $v1[0]?></td>
    <td><?php echo $v1[3]?></td>
    <td><?php echo $v1[2]?></td>
    <td><?php echo $v1[1]?></td>
  </tr>
<?php  }}?>

</table>

<h1>Not Enough To Send</h1>
<table width="700" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td>Barcode</td>
    <td>Description</td>
    <td>Should</td>
    <td>Actual</td>
  </tr>
<?php 
if(!empty($this->arrResPart)){
foreach($this->arrResPart as $k2 => $v2) {?>  
  <tr>
    <td><?php echo $v2[0]?></td>
    <td><?php echo $v2[3]?></td>
    <td><?php echo $v2[2]?></td>
    <td><?php echo $v2[1]?></td>
  </tr>
<?php  }}?>
</table>

<h1>Empty On Hand / Never Send Anything</h1>

<table width="700" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td>Barcode</td>
    <td>Description</td>
    <td>Should</td>
    <td>Actual</td>
  </tr>
  
<?php 
if(!empty($this->arrResEmpty)){
foreach($this->arrResEmpty as $k3 => $v3) {?>  
  <tr>
    <td><?php echo $v3[0]?></td>
    <td><?php echo $v3[2]?></td>
    <td><?php echo $v3[1]?></td>
    <td>0</td>
  </tr>
<?php  }}?>

</table>
<?php	
	}
?>


</body>
</html>
