<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
<h1>Over Stock List </h1>
<table width="1000" border="1" cellspacing="1" cellpadding="5">
  <tr>
    <th scope="col">SOCDE</th>
    <th scope="col">DES</th>
    <th scope="col">On Hand</th>
  </tr>
<?php foreach($this->arrRes as $v){?>  
  <tr>
    <td><?php echo $v[0];?></td>
    <td><?php echo $v[0];?></td>
    <td><?php echo $v[1];?></td>
  </tr>
<?php }?>  
</table>
<!--
<h1>Not Enough Sales List</h1>
<table width="1000" border="1" cellspacing="1" cellpadding="5">
  <tr>
    <th scope="col">SOCDE</th>
    <th scope="col">DES</th>
    <th scope="col">Sales 2Wk Ago</th>
    <th scope="col">Sales Last Wk</th>
    <th scope="col">Average</th>
    <th scope="col">On Hand</th>
    <th scope="col">WH Stock</th>
  </tr>
<?php /*foreach($this->arrRes2 as $v){?>  
  <tr>
    <td><?php echo $v[0];?></td>
    <td><?php echo $v[1];?></td>
    <td><?php echo $v[2];?></td>
    <td><?php echo $v[3];?></td>
    <td><?php echo $v[4];?></td>
    <td><?php echo $v[5];?></td>
    <td><?php echo $v[6];?></td>
  </tr>
<?php } */?>  
</table>
-->

</body>
</html>
