<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<table width="1000" border="1" cellspacing="2" cellpadding="2">
  <tr>
    <td>Warehouse Transfer Today</td>
  </tr>
  <tr>
    <td>item TItle | Barcode | Qty</td>
  </tr>
<?php
$products = new Model_DbTable_Productsva();

foreach($this->smove as $key => $value){
?>  
  <tr>
    <td><?php 
	
	$prow = $products->getProduct($value['id_product']);
	
	echo $prow['code_product'];
	echo " - ";
	echo $prow['title_product'];
	//echo " - ";
	//echo $prow['date_introduce'];	
	echo "   -".$value['qty_product']; 
	
	   ?></td>
  </tr>
<?php
}

 ?>
</table>
</body>
</html>
