<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif; font-size:16px;">
<h1> Last Week Sales System</h1>
<h3> <a href="/products/import" target="_blank">Import All Files First</a></h3>
<table width="600" border="0" cellspacing="1" cellpadding="10">
  <tr>
    <th scope="col">OLD APOS</th>
    <th scope="col">NEW APOS</th>
  </tr>
  <tr>
    <th colspan="2" scope="col">Page Will Pop Up Download Link When Done<br />
      You may do Multiple Shop At Same Time</th>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/ADPC" target="_blank" >ADPC</a></td>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/BSXP" target="_blank" >BSXP</a></td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/BBPC" target="_blank" >BBPC</a></td>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/CLIC" target="_blank" >CLIC</a></td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/BHPC" target="_blank" >BHPC</a></td>
    <td><a href="#" target="_blank" >CSIC</a></td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/BSIC"  target="_blank" >BSIC</a></td>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/DCIC"  target="_blank" >DCIC</a></td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/BSPC"  target="_blank" >BSPC</a></td>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/FGIC"  target="_blank" >FGIC</a></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/HPIC" target="_blank" >HPIC</a></td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/CLPC" target="_blank" >CLPC</a></td>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/PMIC" target="_blank" >PMIC</a></td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/EPPC" target="_blank" >EPPC</a></td>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/CBPC" target="_blank" >CBPC</a></td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/KCPC" target="_blank" >KCPC</a></td>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/EPIC" target="_blank">EPIC</a></td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/NLPC" target="_blank" >NLPC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/PMPC" target="_blank" >PMPC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/SLIC" target="_blank" >SLIC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/WBIC" target="_blank" >WBIC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/WBPC" target="_blank" >WBPC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/WGIC" target="_blank" >WGIC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/WGPC" target="_blank" >WGPC</a></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><a href="http://192.168.1.126/products/generate-weeks-order/shop/WLIC" target="_blank" >WLIC</a></td>
    <td>&nbsp;</td>
  </tr>
</table>

</body>
</html>
