<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif">
<h1>Shop Stop Sale History List (V1.0)</h1>
<table width="800" border="1" cellspacing="1" cellpadding="5">
  <tr>
    <th scope="col">Image</th>
    <th scope="col">Barcode</th>
    <th scope="col">Description</th>
    <th scope="col">Date</th>
    <th scope="col">Reason</th>
  </tr>
<?php foreach($this->sList as $k => $v){?>  
  <tr>
    <td>
        <?php
    $fileStr = getcwd()."/product_img/home_img/".trim($v["barcode"])."_0.jpg";
	if(file_exists($fileStr)){
	?>
    <img src="/product_img/home_img/<?php echo trim($v["barcode"]) ?>_0.jpg" width="100" height="100"  / >    
    <?php	
		}
	?>
    </td>
    <td><?php echo $v["barcode"]?></td>
    <td><?php echo $v["description"]?></td>
    <td><?php echo $v["date"]?></td>
    <td><?php echo $v["comment"]?></td>
    
  </tr>
<?php }?>
</table>

</body>
</html>
