<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<p>Upload APOS CSV EXPORT FILE </p>
<p>Today is <?php  echo Model_DatetimeHelper::dateToday() ;?></p>
<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
  <label for="file_upload"></label>
  <input type="file" name="file_upload" id="file_upload" />
  <input type="submit" name="submit" id="submit" value="Submit" />
</form>
<p>&nbsp;</p>
</body>
</html>
