<?php

header("Expires: Mon, 26 Jul 1970 05:00:00 GMT");      
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");      
header("Cache-Control: no-cache, must-revalidate");      
header("Pragma: no-cache");  

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="/js/bankin_0120.js"></script>
</head>

<body style=" font-family:Arial, Helvetica, sans-serif;">
<h1>ONLY RECORD WHAT YOU BANKED IN<br />
DO NOT RECORD ANY CASHOUT AMOUNT</h1>
<form id="form1" name="form1" method="post" action="">
<table width="800" border="1" cellspacing="0" cellpadding="5">

  <tr>
    <td>Date</td>
    <td>Amount</td>
    <td>Deposited</td>
    <td>Banked In  Today</td>

  </tr>

<?php foreach($this->arrDpRecord as $key => $v) {?>
  <tr>
    <td><?php echo $v['0']?></td>
    <td><?php echo ($v['1'] >0)?"$ {$v[1]}":" [Cash Out] $ {$v['2']} "; ?></td>
    <td><?php echo ($v['3'])?"YES ( $ {$v[4][0]['amt_bankin']})":"X";?></td>
    <td><?php echo ($v['3'])?"-":"<input type=\"checkbox\" name=\"bi_confirm[{$v[0]}]\" id = \"bi_confirm{$v[0]}\" value=\"1\" /> <input type=\"text\" value=\"{$v['1']}\" name=\"bi_amt[$v[0]]\" id=\"bi_amt{$v[0]}\" />" ?>  $ </td>
  </tr>
<?php }?>
</table>
<br />
<br />

  <label for="diff_date">Total Bank In Today </label>
  <input type="text" name="total_bkin" id="total_bkin" readonly="readonly" /> $ 
  <br />
<?php if($this->showDateDep){?>  
  <br />
 Bank In Date: <input type="text" name="diff_date" id="diff_date" />
<br />
<?php }?>
  <br />
  Bank In Comment:<br />
  <br />
  <label for="manager_comment"></label>
  <textarea name="manager_comment" cols="100" rows="3" id="manager_comment"></textarea>
  <br />
  <br />
  Your Attendance Password 
   <label for="manager_pwd"></label>
  <input type="password" name="manager_pwd" id="manager_pwd" />
  <br />
  <br />
  <input type="submit" name="button" id="button" value="Submit" />
  <br />
</form>
<br />
</body>
</html>
