<?php
if(!$this->output){
?>
<table width="600" border="1" cellspacing="0" cellpadding="0" align="center" style="margin-top:100px; border:#036 1px solid; font-family:Arial;">
  <tr>
    <td style="height:200px; background-color:#C6E6FF; text-align:center; vertical-align:middle;">
    The Opening of This Shop For Today is Missing , Summay will NOT creat. The Closing Information has been Saved, You may Now Close this window.
    
    </td>
  </tr>
</table>
<?php }
else{
	echo $this->output;
	}
?>
