<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>

<link href="/css/1pxtable.css" rel="stylesheet" type="text/css" media="all" />
<link type="text/css" href="/css/start/jquery-ui-1.8.21.custom.css" rel="Stylesheet" />	
<script type="text/javascript" src="/js/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.21.custom.min.js"></script>

</head>
<body style="font-family:Arial, Helvetica, sans-serif">
<script>
	$(function() {
		$( "#paid_date_cash" ).datepicker({ dateFormat: "yy-mm-dd",firstDay: 1 });
		$( "#paid_date_bank" ).datepicker({ dateFormat: "yy-mm-dd",firstDay: 1 });
	});
	</script>
    
<h3>Bonus Of This Month </h3>
<p>Cash <br />
</p>
<form method="post" action="" >
<table width="256" border="1" cellspacing="0" cellpadding="5" style="font-size:13px;">
<tr>
<td width="115">Save delay date</td>
<td width="115">Cancel the staff</td>
</tr>
<td><input type="submit" name="save_bt" id="save_bt" value="Save" /></td>
<td><input type="submit" name="cancel_bt" id="cancel_bt" value="Cancel"/></td>
</table>
<br />
<table width="1557" border="1" cellspacing="0" cellpadding="5" style="font-size:13px;">
  <tr>
    <td width="65" style="width:65px;">ID Bonus</td>
    <td width="120" style="width:120px;">Staff</td>
    <td width="150" style="width:150px;">Bonus Type</td>
    <td width="100" style="width:100px;">Total Amt</td>
    <td width="180" style="width:180px;">Period</td>
    <td colspan="2" style="width:100px;">Will Pay On</td>
    <td width="45">Cancel</td>
    <td width="219">Cancel Reason</td>
    <td width="240">Comment</td>
  </tr>
  <?php 
  $stDetail = new Model_DbTable_Roster_Stafflogindetail();
  $btype = new Model_Payroll_Staffbonustype();
  
  
  foreach($this->bList as $k => $v){
	if($v['pay_type'] == 1 && $v['hold_to_date']=='0000-00-00' ){
		$btypeRow = $btype->getStaffbonustype($v['type_bonus']);
		$sdRow = $stDetail->getDetail($v['id_staff']);
		$nName = $sdRow['ni'];
		$fName = Model_EncryptHelper::getSslPassword($sdRow['n']);
		
	  ?>
  <tr>
    <td><?php echo $v['id_bonus']?></td>
    <td><?php echo ucwords($nName." <br />[ ".$fName." ]");?></td>
    <td><?php echo $btypeRow['type_bonus']?></td>
    <td align="left">$ <?php echo $v['amt_total_bonus']?></td>
    <td><?php echo $v['period_bonus_begin']." to ".$v['Period_bonus_end'];?></td>
    <td width="20"><input type="checkbox" name="check_delay[<?php echo $v['id_bonus']?>]" id="check_delay<?php echo $v['id_bonus']?>" value="<?php echo $v['id_bonus']?>" />
    <td width="144"><input type="text" name="date_delay[<?php echo $v['id_bonus']?>]" id="date_delay<?php echo $v['id_bonus']?>" value="<?php echo $v['pay_date'];?>"  /></td>
    <td>
    <input type="checkbox" name="check_cancel[<?php echo $v['id_bonus']?>]" id ="check_cancel[<?php echo $v['id_bonus']?>]" value= "cancel" />
    </td>
    <td><input name="cancel_reason[<?php echo $v['id_bonus']?>]" id="cancel_reason[<?php echo $v['id_bonus']?>]" type="text" style="width: 210px"/></td>
    <td><?php echo $v['detail_bonus']?></td>
  </tr>
 <?php 
	}
 }?> 
</table>
</form>
<br />
Bank
<br />
<br />
<form method="post" action="" >
<table width="256" border="1" cellspacing="0" cellpadding="5" style="font-size:13px;">
<tr>
<td width="115">Save delay date</td>
<td width="115">Cancel the staff</td>
</tr>
<td><input type="submit" name="save_bt" id="save_bt" value="Save" /></td>
<td><input type="submit" name="cancel_bt" id="cancel_bt" value="Cancel"/></td>
</table>
</br>

<table width="1557" border="1" cellspacing="0" cellpadding="5" style="font-size:13px;">
  <tr>
    <td width="65" style="width:65px;">ID Bonus</td>
    <td width="120" style="width:120px;">Staff</td>
    <td width="150" style="width:150px;">Bonus Type</td>
    <td width="100" style="width:100px;">Total Amt</td>
    <td width="100" style="width:100px;">Pay Bank</td>
    <td width="100" style="width:100px;">Super</td>
    <td width="180" style="width:180px;">Period</td>
    <td colspan="2" style="width:100px;">Will Pay On</td>
    <td width="50" style="width:50px;">Cancel</td>
    <td width="200" style="width:170px;">Cancel Reason</td>
    <td width="180" style="width:200px;">Comment</td>
  </tr>
  <?php 
  $stDetail = new Model_DbTable_Roster_Stafflogindetail();
  $btype = new Model_Payroll_Staffbonustype();
  
  
  foreach($this->bList as $k => $v){
	if($v['pay_type'] == 2 && $v['hold_to_date']=='0000-00-00' ){
		$btypeRow = $btype->getStaffbonustype($v['type_bonus']);
		$sdRow = $stDetail->getDetail($v['id_staff']);
		$nName = $sdRow['ni'];
		$fName = Model_EncryptHelper::getSslPassword($sdRow['n']);
		
		
	  ?>
  <tr>
    <td><?php echo $v['id_bonus']?></td>
    <td><?php echo ucwords($nName." <br />[ ".$fName." ]");?></td>
    <td><?php echo $btypeRow['type_bonus']?></td>
    <td align="left">$ <?php echo $v['amt_total_bonus']?></td>
    <td align="left">$ <?php echo $v['amt_bank_bonus']?></td>
    <td align="left">$ <?php echo $v['amt_bonus_super']?></td>
    <td><?php echo $v['period_bonus_begin']." to ".$v['Period_bonus_end'];?></td>
    <td width="20"><input type="checkbox" name="check_delay[<?php echo $v['id_bonus']?>]" id="check_delay<?php echo $v['id_bonus']?>" value="<?php echo $v['id_bonus']?>" />
    <td width="144"><input type="text" name="date_delay[<?php echo $v['id_bonus']?>]" id="date_delay<?php echo $v['id_bonus']?>" value="<?php echo $v['pay_date'];?>"  /></td>
    <td>
    <input type="checkbox" name="check_cancel[<?php echo $v['id_bonus']?>]" id ="check_cancel[<?php echo $v['id_bonus']?>]" value= "cancel" />
    </td>
    <td><input name="cancel_reason[<?php echo $v['id_bonus']?>]" id="cancel_reason[<?php echo $v['id_bonus']?>]" type="text" style = "width:180px"/></td>
    <td><?php echo $v['detail_bonus']?></td>
  </tr>
 <?php 
 
	}
 }?> 
</table>
<form method="post" action="" >

<h3>Hold Bonus Of This Month, Will Not Release And Show</h3>
<p>Cash <br />
</p>
<table width="1557" border="1" cellspacing="0" cellpadding="5" style="font-size:13px;">
  <tr>
    <td style="width:65px;">ID Bonus</td>
    <td style="width:120px;">Staff</td>
    <td style="width:150px;">Bonus Type</td>
    <td style="width:100px;">Total Amt</td>
    <td style="width:180px;">Period</td>
    <td colspan="2" style="width:100px;">Plan Release</td>
    <td style="width:100px;">Hold Until</td>
    <td>Comment</td>
    <td>Hold Reason</td>
    <td>Release/Cancel Comment</td>
    <td>Cancel <br />
      Forever</td>
  </tr>
  <?php 
  $stDetail = new Model_DbTable_Roster_Stafflogindetail();
  $btype = new Model_Payroll_Staffbonustype();
  
  
  foreach($this->hList as $k => $v){
	if($v['pay_type'] == 1 && $v['hold_to_date']!='0000-00-00' ){
		$btypeRow = $btype->getStaffbonustype($v['type_bonus']);
		$sdRow = $stDetail->getDetail($v['id_staff']);
		$nName = $sdRow['ni'];
		$fName = Model_EncryptHelper::getSslPassword($sdRow['n']);
		
	  ?>
  <tr>
    <td><?php echo $v['id_bonus']?></td>
    <td><?php echo ucwords($nName." <br/> [ ".$fName." ]");?></td>
    <td><?php echo $btypeRow['type_bonus']?></td>
    <td align="left">$ <?php echo $v['amt_total_bonus']?></td>
    <td><?php echo $v['period_bonus_begin']." to ".$v['Period_bonus_end'];?></td>
    <td><input type="checkbox" name="check_release[<?php echo $v['id_bonus']?>]" id="check_release<?php echo $v['id_bonus']?>" value="<?php echo $v['id_bonus']?>" />     </td>
    <td>
    <input type="text" name="date_release[<?php echo $v['id_bonus']?>]" id="date_release<?php echo $v['id_bonus']?>" value="<?php echo $v['pay_date']?>"  /></td>
    <td><?php echo $v['hold_to_date']?></td>
    <td><?php echo $v['detail_bonus']?></td>
    <td><?php echo $v['hold_reason']?></td>
    <td><label for="release_comment"></label>
      <textarea name="release_comment[<?php echo $v['id_bonus']?>]" rows="2" id="release_comment<?php echo $v['id_bonus']?>" style = "width:230px"></textarea></td>
    <td><input type="checkbox" name="check_cancel[<?php echo $v['id_bonus']?>]" id="check_cancel<?php echo $v['id_bonus']?>" value="1" />
      <label for="check_cancel"></label></td>
  </tr>
 <?php 
	}
 }?> 
</table>
<br />
Bank
<br />
<br />
<table width="1557" border="1" cellspacing="0" cellpadding="5" style="font-size:13px;">
  <tr>
    <td width="65" style="width:65px;">ID Bonus</td>
    <td width="120" style="width:120px;">Staff</td>
    <td width="150" style="width:150px;">Bonus Type</td>
    <td width="100" style="width:100px;">Total Amt</td>
    <td width="100" style="width:100px;">Pay Bank</td>
    <td width="100" style="width:100px;">Super</td>
    <td width="180" style="width:180px;">Period</td>
    <td colspan="2" style="width:100px;">Plan Release</td>
    <td width="100" style="width:100px;">Hold Until</td>
    <td width="56">Comment</td>
    <td width="44">Hold Reason</td>
    <td width="161">Release/Cancel Comment</td>
    <td width="47">Cancel<br />
      Forever</td>
  </tr>
  <?php 
  $stDetail = new Model_DbTable_Roster_Stafflogindetail();
  $btype = new Model_Payroll_Staffbonustype();
  
  
  foreach($this->hList as $k => $v){
	if($v['pay_type'] == 2 && $v['hold_to_date']!='0000-00-00' ){
		$btypeRow = $btype->getStaffbonustype($v['type_bonus']);
		$sdRow = $stDetail->getDetail($v['id_staff']);
		$nName = $sdRow['ni'];
		$fName = Model_EncryptHelper::getSslPassword($sdRow['n']);
		
	  ?>
  <tr>
    <td><?php echo $v['id_bonus']?></td>
    <td><?php echo ucwords($nName."<br /> [ ".$fName." ]");?></td>
    <td><?php echo $btypeRow['type_bonus']?></td>
    <td align="left">$ <?php echo $v['amt_total_bonus']?></td>
    <td align="left">$ <?php echo $v['amt_bank_bonus']?></td>
    <td align="left">$ <?php echo $v['amt_bonus_super']?></td>
    <td><?php echo $v['period_bonus_begin']." to ".$v['Period_bonus_end'];?></td>
    <td width="20"><input type="checkbox" name="check_release[<?php echo $v['id_bonus']?>]" id="check_release<?php echo $v['id_bonus']?>"  value="<?php echo $v['id_bonus']?>" /></td>
    <td width="144"><input type="text" name="date_release[<?php echo $v['id_bonus']?>]" id="date_release<?php echo $v['id_bonus']?>"  value="<?php echo $v['pay_date']?>"  /></td>
    <td><?php echo $v['hold_to_date']?></td>
    <td><?php echo $v['detail_bonus']?></td>
    <td><?php echo $v['hold_reason']?></td>
    <td><textarea name="release_comment[<?php echo $v['id_bonus']?>]" rows="2" id="release_comment<?php echo $v['id_bonus']?>"></textarea></td>
    <td><input type="checkbox" name="check_cancel[<?php echo $v['id_bonus']?>]" id="check_cancel<?php echo $v['id_bonus']?>" value="2" /></td>
  </tr>
  <?php 
	}
 }?>
</table>
<br />


<input name="btn_release" type="submit" id="btn_release" value="Release / Cancel Selected Bonus" />


</form>
</body>
</html>
