<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width; initial-scale=1; maximum-scale=1.0; user-scalable=0;" />
<title>Untitled Document</title>
<style>
.act{
	width:70px;
	height:50px;
	margin:5px;
	background-color:#0C3;
	font-size:18px;
	font-weight:bold;
	text-align:center;
	line-height:50px;
	display:inline-block
	}
.dis{
	width:70px;
	height:50px;
	margin:5px;
	background-color:#ccc;
	color:#999;
	font-size:18px;
	text-align:center;
	line-height:50px;
	display:inline-block
	}
.done{
	width:70px;
	height:50px;
	margin:5px;
	background-color:#339;
	color:#666;
	font-size:18px;	
	text-align:center;
	line-height:50px;
	display:inline-block
	}	
	
</style>
</head>

<body style="margin:5px;">
<form id="form1" name="form1" method="post" action="">
  <table width="320" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <th scope="col" align="left">
	<?php
	$arrShop = array();
    foreach($this->stList as $key => $v){
	
	if(!in_array($v[0],$arrShop)){
		$arrShop[]= $v[0];
	?>
    
    <input name="<?=$v[0]?>" type="submit" 
    <?php if($v[1]==""){echo 'class="act"';}
	else{echo 'class="done" disable="disable"';}
	?>
     value="<?=$v[0]?>" />
    <?
	
	}
		}
	?>           
      </th>
    </tr>
  </table>
</form>
</body>
</html>
