<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<h1>Edit Location</h1>
<form action="" method="post">
<table width="800" border="1" cellspacing="0" cellpadding="10">
  <tr>
    <th rowspan="2" align="left" style="width:30%">Location Code :
    <input type="text" name="location_code" id="location_code" /></th>
    <th colspan="2" align="left" scope="col"><input type="button" name="btn_a" id="btn_a" value="A" />
    <input type="button" name="btn_b" id="btn_b" value="B" />
    <input type="submit" name="btn_c" id="btn_c" value="C" />
    <input type="submit" name="btn_d" id="btn_d" value="D" />
    <input type="submit" name="btn_e" id="btn_e" value="E" />
    <input type="submit" name="btn_f" id="btn_f" value="F" />
    <input type="submit" name="btn_g" id="btn_g" value="G" /> | 
    <input type="submit" name="btn_x" id="btn_x" value=" X " />
    <input type="submit" name="btn_y" id="btn_y" value=" Y " />
    <input type="submit" name="btn_h" id="btn_h" value=" H " />    </th>
  </tr>
  <tr>
    <th colspan="2" align="left" scope="col">
    <input type="button" name="btn_0" id="btn_0" value="0" />
    <input type="button" name="btn_1" id="btn_1" value="1" />
    <input type="button" name="btn_2" id="btn_2" value="2" />
    <input type="button" name="btn_3" id="btn_3" value="3" />
    <input type="button" name="btn_4" id="btn_4" value="4" />
    <input type="button" name="btn_5" id="btn_5" value="5" />
    <input type="button" name="btn_6" id="btn_6" value="6" />
    <input type="button" name="btn_7" id="btn_7" value="7" />
    <input type="button" name="btn_8" id="btn_8" value="8" />
    <input type="button" name="btn_9" id="btn_9" value="9" /></th>
  </tr>
  <tr>
    <td align="center">Stock Location
      <input type="radio" name="code_location" id="radio" value="SL" />
    <label for="code_location"></label></td>
    <td align="center">Bulk Location
      <input type="radio" name="code_location" id="radio2" value="BKL" /></td>
    <td align="center">Box Number
    <input type="radio" name="code_location" id="radio3" value="BN" /></td>
  </tr>
  <tr>
    <td colspan="3" align="center" valign="top">
      <label for="barcodes">Scan Barcode</label>
      <br />
      
      <textarea name="barcodes" id="barcodes" cols="90" rows="3"></textarea></td>
  </tr>
  <tr>
    <td colspan="3" align="center" valign="top"><input type="submit" name="btn_save" id="btn_save" value="Save" /></td>
  </tr>
</table>
</form>
Barcode List In the Location<br />
<table width="600" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <th scope="col">Image</th>
    <th scope="col">Code</th>
    <th scope="col">Title</th>
    <th scope="col">Act</th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>X</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>X</td>
  </tr>
</table>
</body>
</html>
