<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif; font-size:14px;">
<table width="1000" border="1" cellspacing="0" cellpadding="10">
  <tr>
    <td>NO</td>
    <td>Code</td>
    <td>Descript</td>
  </tr>
  <?php 
  $cot = 0;
  foreach($this->arrNoLoc as $code => $des){
	  
	  ?>
  <tr>
    <td><?php echo $cot++;?></td>
    <td><?php echo $code;?></td>
    <td><?php echo $des;?></td>
   <?php }?> 
  </tr>
  
</table>
</body>
</html>
