<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>ERROR ERROR ERROR</title>
  <style type="text/css">
<!--
.style1 {
	font-size: 100px;
	color: #CCFF00;
}
.style4 {font-size: 12px; color: #999999; }
.style6 {font-size: 12px; color: #0066FF; }
-->
  </style>
</head>
<body style="font-family: arial;">
  <h1 align="center"><span class="style1"><img src="/im/error.png" title="An Error Occurred"  /><br />
  OOPS!</span><br /> 
    <span class="style4">An ERROR occurred</span><br />
  <span class="style6">please Contact me for Support, ASAP</span></h1>
</body>
</html>
