<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif; font-size:12px;">
<form action="" method="post" enctype="multipart/form-data" name="form1" id="form1">
  <label for="textfield"></label>Which Statement is Come From  
  <label for="state_id"></label>
  <select name="state_id" id="state_id">
    <option value="1" selected="selected">IC Statement</option>
    <option value="2">PC Statement</option>
    <option value="3">New Gen Statement</option>
  </select>
  <br />
  <label for="upload_file"></label>
  <input type="file" name="upload_file" id="upload_file" />
  <input type="submit" name="button" id="button" value="Submit" />

</form>
<br />
<h2>Found And Recorded</h2>
<table width="600" border="1" cellspacing="0" cellpadding="5">
  <tr>
    <td>Shop</td>
    <td>Date</td>
    <td>$Amt</td>
  </tr>
 <?php foreach($this->arrFound as $rowFound){?> 
  <tr>
    <td><?php echo $rowFound[0]?></td>
    <td><?php echo $rowFound[1]?></td>
        <td><?php echo $rowFound[2]?></td>
  </tr>
 <?php }?> 
</table>
<h2>We have Deposite but Not Match Bank In Detail </h2>
<table width="700" border="1" cellspacing="0" cellpadding="5">
  <tr>
    <td>Shop</td>
    <td>Date</td>
    <td>$Amt</td>
  </tr>
 <?php foreach($this->arrNotFound as $rownotFound){?> 
  <tr>
    <td><?php echo $rownotFound[0]?>&nbsp;&nbsp;<span style="font-size:12px">[<?php echo $rownotFound[3]?>]</span></td>
    <td><?php echo $rownotFound[1]?></td>
        <td><?php echo $rownotFound[2]?> (<?php echo $rownotFound[4]?> )</td>
  </tr>
 <?php }?> 
</table>
</body>
</html>
