<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>
<p>Shop / Date/ Who/ Amt/ Time / Find in EFT/ Invoice / time / Find in Cash / Invoice/ Time / Staff Mark / Apos / Remark</p>
<table width="1600" border="1" cellspacing="0" cellpadding="15">
  <tr>
    <td>No</td>
    <td>Shop</td>
    <td>Date</td>
    <td>Who</td>
    <td>Amount</td>
    <td>Time</td>
    <td>Find EFT</td>
    <td>Invoice</td>
    <td>Time</td>
    <td>Find Cash</td>
    <td>Invoice </td>
    <td>Time</td>
    <td>Staff Input</td>
    <td>Apos</td>
    <td>Remark</td>
    <td>&nbsp;</td>
  </tr>
  <?php foreach($this->arrRes as $key => $v){?>
  <tr>
    <td><?php echo $key + 1;?></td>
    <td><?php echo $v[0]?></td>
    <td><?php echo $v[1]?></td>
    <td><?php echo $v[2]?></td>
    <td><?php echo $v[3]?></td>
    <td><?php echo $v[4]?></td>
    <td><?php echo $v[5]?></td>
    <td><?php echo $v[6]?></td>
    <td><?php echo $v[7]?></td>
    <td><?php echo $v[8]?></td>
    <td><?php echo $v[9]?></td>
    <td><?php echo $v[10]?></td>
    <td><?php echo $v[11]?></td>
    <td><?php echo $v[12]?></td>
    <td><?php echo $v[13]?></td>
    <td>&nbsp;</td>
  </tr>
<?php }?>
</table>
<p>&nbsp;</p>
</body>
</html>
