<style>
.table-print{
	width:200mm;
	font-family:Arial, Helvetica, sans-serif;
	font-size:4mm;
	line-height:8mm;
	}
</style>
<body onLoad="window.print()">
<?php
$order = $this->order;
?>				
<h1 style="font-family:Arial, Helvetica, sans-serif"><?=$order["order_no"]?></h1>
<span style="font-family:Arial, Helvetica, sans-serif"><?php echo " Created by ".$order["staff_name"]." On ".$order["order_create_date"];?></span><br>

<table  border="1" cellspacing="0" cellpadding="0" class="table-print">
  <tr>
    <th scope="col" style="text-align:left; padding-left:4mm; width:40mm;" >Barcode</th>
    <th scope="col" style="text-align:left; padding-left:4mm;" >Title</th>
    <th scope="col" style="text-align:left; padding-left:4mm; width:20mm;" >Qty</th>
  </tr>
<?php
$products = new Model_DbTable_Productsva();
 foreach($this->pList as $v){
	$productRow = $products->getProduct($v["id_product"]);
	?>  
  <tr>
    <td style="text-align:left; padding-left:4mm;" ><?=$productRow["code_product"]?></td>
    <td style="text-align:left; padding-left:4mm;"><?=$productRow["title_product"]?></td>
    <td style="text-align:left; padding-left:4mm;"><?=$v["qty_order"]?></td>
  </tr>
<?php }?>
</table>
</body>
