<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>

<form action="" method="post">
  <p>Staff ID:
    <label for="id_staff"></label>
    <input type="text" name="id_staff" id="id_staff" />
  </p>
  <p>Date Begin
    <input type="text" name="date_begin" id="date_begin" />
  </p>
  <p>Date End
    <input type="text" name="date_end" id="date_end" />
  </p>
  <p>
    <input type="submit" name="button" id="button" value="Submit" />
  </p>
</form>
</body>
</html>
