<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
/* <![CDATA[ */

table, td
{
    border-color: #666;
    border-style: solid;
}
table, th
{
    border-color: #666;
    border-style: solid;
}

table
{
    border-width: 0 0 1px 1px;
    border-spacing: 0;
    border-collapse: collapse;
}

td
{
    margin: 0;
    padding: 8px;
    border-width: 1px 1px 0 0;
}
th
{
    margin: 0;
    padding: 8px;
    border-width: 1px 1px 0 0;
}

/* ]]> */
</style>
</head>

<body style="font-family:Arial;">
<table width="1000"  cellspacing="0" cellpadding="15">
  <tr>
    <td>ID</td>
    <td>Name (Nick Name)</td>
    <td>Register Date</td>
    <td>Expire Date</td>
    <td>In MYOB</td>
    <td colspan="3">ACTION (Extend Base On Expire Date)</td>
    <td>&nbsp;</td>
  </tr>
 <?php foreach($this->expireList as $key => $v) {?> 
 <form id="form<?php echo $v['id']?>" name="form<?php echo $v['id']?>" method="post" action="" >
  <tr>
    <td><?php echo $v['id']?></td>
    <td><?php echo Model_EncryptHelper::getSslPassword($v['n'])." (".$v['ni'].")";?></td>
    <td>&nbsp;</td>
    <td><?php echo $v['expire_date']?>
      <input type= "hidden" name="expire_date" id="expire_date" value="<?php echo $v['expire_date']?>" /></td>
    <td><?php echo ($v['in_myob'])?"YES":"NO";?></td>
    <td>
      <input type= "hidden" name="id" id="staff_id" value="<?php echo $v['id']?>" />	
      <input type="submit" name="btn_7days" id="btn_7days" value="Extend Another 7 Days" />
    </td>
    <td><input type="submit" name="btn_14days" id="btn_14days" value="Extend Another 14 Days" /></td>
    <td><input type="submit" name="btn_never" id="btn_never" value="Never Expire" /></td>
    <td>&nbsp;</td>
  </tr>
  </form>
 <?php }?> 
</table>
</body>
</html>
