<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial;">
<h1>Faulty Shop :<?php echo $_GET['shop_code'];?></h1>
<?php echo $_GET['date_begin'] ?>  to <?php echo $_GET['date_end'] ?> <br />

<?php 

	
?>
<table width="888" border="0" cellspacing="1" cellpadding="5" bgcolor="#666666">
  <tr>
    <td bgcolor="#FFFFFF">BarCode</td>
    <td bgcolor="#FFFFFF" width="99">Staff Name</td>
    <td bgcolor="#FFFFFF" width="100">Date</td>
    <td bgcolor="#FFFFFF">Pcs</td>    
    <td bgcolor="#FFFFFF">Comment</td>
    <td bgcolor="#FFFFFF">Audit Comment</td>

  </tr>
<?php 

foreach($this->fproductrow as $key => $value){

	
	?>  
  <tr>
    <td bgcolor="#FFFFFF"><a href="#" title="<?php echo $value['product_name_faulty']?>"><?php echo $value['product_code_faulty']?></a></td>
    <td bgcolor="#FFFFFF"><?php echo $value['staff_name_faulty']?> </td>
    <td bgcolor="#FFFFFF"><?php echo $value['date_faulty']?></td>
    <td bgcolor="#FFFFFF"><?php echo $value['faulty_qty']?></td>    
    <td bgcolor="#FFFFFF"><?php echo $value['comment_faulty']?></td>
    <td bgcolor="#FFFFFF">
	
	<?php 
	if($value['audit_faulty'] ==0){echo "U |";}
	if($value['audit_faulty'] ==2){echo "R |";}
	echo $value['audit_comment'];?>
    </td>

  </tr>
<?php

}
?>  
  
  <tr>
    <td bgcolor="#FFFFFF">BarCodw</td>
    <td bgcolor="#FFFFFF">Staff Name</td>
    <td bgcolor="#FFFFFF">Date</td>
    <td bgcolor="#FFFFFF">Pcs</td>    
    <td bgcolor="#FFFFFF">Comment</td>
    <td bgcolor="#FFFFFF">Audit Comment</td>

  </tr>
</table>

</body>
</html>
