<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif;">
<table width="1000" border="0" cellspacing="1" cellpadding="5" bgcolor="#333333">
  <tr>
    <td bgcolor="#FFFFFF">Creatation</td>
    <td bgcolor="#FFFFFF">Warehouse <br />
    Initial Process</td>
    <td bgcolor="#666666">&nbsp;</td>
    <td bgcolor="#FFFFFF">Admin<br />
      Follow Up</td>
    <td bgcolor="#FFFFFF">Case Close</td>
  </tr>
  <tr>
    <td rowspan="6" bgcolor="#FFFFFF"><a href="/faultyaudit/" target="_blank">RMA</a></td>
    <td bgcolor="#FFFFFF"><p>[1]Canceled Key in Error<br />
      <br />
    </p></td>
    <td bgcolor="#666666">&nbsp;</td>
    <td bgcolor="#FFFFFF">&nbsp;</td>
    <td bgcolor="#FFFFFF">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#FFFFFF"><p>[2] Rejected Return to Shop(Print Email)<br />
      <br /></p></td>
    <td bgcolor="#666666">&nbsp;</td>
    <td bgcolor="#FFFFFF">&nbsp;</td>
    <td bgcolor="#FFFFFF">Dipatched Through Goods Delivery</td>
  </tr>
  <tr>
    <td bgcolor="#FFFFFF">[3] <a href="/faultyaudit/print-dispose-list" target="_blank">Disponse</a><br />      <br />
    </td>
    <td bgcolor="#666666">&nbsp;</td>
    <td bgcolor="#FFFFFF">&nbsp;</td>
    <td bgcolor="#FFFFFF">Disposed [<a href="/faultyaudit/list-final-status/code/FDP">Check Dispose Lists</a>]</td>
  </tr>
  <tr>
    <td bgcolor="#FFFFFF">[4]<a href="/faultyaudit/print-return-supplier" target="_blank">Return To Supplier</a><br />
    <br /></td>
    <td bgcolor="#666666">&nbsp;</td>
    <td bgcolor="#FFFFFF">[4.1]<a href="/faultyaudit/submit-rma" target="_blank">Apply RMA</a><br />
    <br />
    [4.2] <a href="/faultyaudit/post-back" target="_blank">Post Back</a><br />
    <br />
    [4.3]<a href="/faultyaudit/list-wait-credit" target="_blank">Manage Credit</a><br /></td>
    <td bgcolor="#FFFFFF">Credit Received<br />
    [Check Credit Note List]<br />
    [Check All Supplier RMA]<br />
    [Check All Tracking No]<br /></td>
  </tr>
  <tr>
    <td bgcolor="#FFFFFF">
[5]
    <a href="/faultyaudit/print-return-china" target="_blank">Return to China</a><br />
    <br /></td>
    <td bgcolor="#666666">&nbsp;</td>
    <td bgcolor="#FFFFFF">&nbsp;</td>
    <td bgcolor="#FFFFFF">Returned [<a href="/faultyaudit/list-final-status/code/FCN">Check Return China List</a>]</td>
  </tr>
  <tr>
    <td bgcolor="#FFFFFF">
[6] <a href="/faultyaudit/print-transfer-online" target="_blank">Sale Online/Other</a><br />
<br /></td>
    <td bgcolor="#666666">&nbsp;</td>
    <td bgcolor="#FFFFFF">&nbsp;</td>
    <td bgcolor="#FFFFFF">Transfered[<a href="/faultyaudit/list-final-status/code/FSL">Check Transfer list</a>]</td>
  </tr>
</table>
</body>
</html>
