<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Online RMA Lodgement System</title>
<link href="/css/template.css" rel="stylesheet" type="text/css" />
</head>

<body>
<table width="600" border="0" cellspacing="0" cellpadding="10" align="center">

  <tr>
    <td><a title="Phone Collection" href="http://www.newgenerationgroup.com.au/index.php"> <img id="logo" src="http://www.newgenerationgroup.com.au/images/logo-phone-collection.png" alt="Phone Collection" border="0" /></a></td>
  </tr>
  <tr>
    <td class="theh1" ><p>Phone Collection Online RMA Auditing System For Warehouse</p>
      <p>&nbsp;</p>
      <p><br />
      <form action="" method="post"><input name="id_rma" type="text" />
          <input type="submit" name="btn_reset" id="btn_reset" value="Rest RMA" />
        </form>
        
        <br />
      </p></td>
  </tr>
  <tr>
    <td align="left" valign="middle"><span style="font-weight:bold;">IN VICTORIA</span></td>
  </tr>
  <tr>
    <td align="center" valign="middle"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td style="width:200px;"><span class="theh1" >Phone Collection</span></td>
        <td style="line-height:30px; text-transform:capitalize;"><a href="/faultyaudit/audit/shop/BSPC" >Bayside Phone Collection</a>[<?php echo $this->count_bspc;?>]<br />
          <a href="/faultyaudit/audit/shop/BHPC">Boxhill Phone Collection</a>[<?php echo $this->count_bhpc;?>]<br />
          <a href="/faultyaudit/audit/shop/BBPC">Brimbank Phone Collection</a>[<?php echo $this->count_bbpc;?>]<br />
          <a href="/faultyaudit/audit/shop/COPC">Corio Phone Collection</a>[<?php echo $this->count_copc;?>]<br />
          <a href="/faultyaudit/audit/shop/CBPC">Cranbourne Phone Collection</a>[<?php echo $this->count_cbpc;?>]<br />
          <a href="/faultyaudit/audit/shop/EPPC">Epping Phone Collection</a>[<?php echo $this->count_eppc;?>]<br />
          <a href="/faultyaudit/audit/shop/FGPC">Fountain Gate Phone Collection</a>[<?php echo $this->count_fgpc;?>]<br />
          <a href="/faultyaudit/audit/shop/HPPC">High Point Phone Collection</a>[<?php echo $this->count_hppc;?>]<br />
          <a href="/faultyaudit/audit/shop/KCPC">Knox City Phone Collection</a>[<?php echo $this->count_kcpc;?>]<br />
          <a href="/faultyaudit/audit/shop/NLPC">Northland Phone Collection</a>[<?php echo $this->count_nlpc;?>]<br />
          <a href="/faultyaudit/audit/shop/PMPC">Parkmore Phone Collection</a>[<?php echo $this->count_pmpc;?>]<br />
          <a href="/faultyaudit/audit/shop/WBPC">Werribee Phone Collection</a>[<?php echo $this->count_wbpc;?>]<br />
          <a href="/faultyaudit/audit/shop/WGPC">Water Garden Phone Collection</a>[<?php echo $this->count_wgpc;?>]<br />          
          <br />        
          </td>
      </tr>
      <tr>
        <td style="width:200px;" ><span class="theh1" >iCollection</span></td>
        <td  style="line-height:30px; text-transform:capitalize;"><p><a href="/faultyaudit/audit/shop/BSIC">Bayside iCollection</a>[<?php echo $this->count_bsic;?>]<br />
          <a href="/faultyaudit/audit/shop/SLIC">Southland iCollection</a>[<?php echo $this->count_slic;?>]<br />
          <a href="/faultyaudit/audit/shop/WGIC">Water Garden iCollection</a>[<?php echo $this->count_wgic;?>]<br />
          <a href="/faultyaudit/audit/shop/WBIC">Werribee iCollection</a>[<?php echo $this->count_wbic;?>]<br />        
          <a href="/faultyaudit/audit/shop/CSIC">Chadston iCollection</a>[]<br />         
          <a href="/faultyaudit/audit/shop/DCIC">Doncaster iCollection</a>[]<br />        
          <a href="/faultyaudit/audit/shop/PMIC">Parkmore iCollection</a>[]<br />       
          <a href="/faultyaudit/audit/shop/BSXP">Bayside Xpress Repair</a>[]<br />        
          <a href="/faultyaudit/audit/shop/FGIC">Fountain Gate iCollection</a>[]</p>
          <p><a href="/faultyaudit/audit/shop/EPIC" target="_self">EPIC</a><br />
            <br />
            <a href="/faultyaudit/audit/shop/ONLI">ONLINE And Warehouse </a></p>
          <p><br />
          </p></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td align="left" valign="middle"><span style="font-weight:bold;" >IN SOUTH AUSTRALIA</span></td>
  </tr>
  <tr>
    <td align="center" valign="middle"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><a href="/faultyaudit/audit/shop/ADPC">Arndale Phone Collection</a>[<?php echo $this->count_adpc;?>]</td>
        <td><a href="/faultyaudit/audit/shop/CLPC">Colonnades Phone Collection</a>[<?php echo $this->count_clpc;?>]<br />
          <br />
          <a href="/faultyaudit/audit/shop/CLIC">Colonnades iCollection</a>[]<br />          
          <br />
          </td>
        <td><a href="/faultyaudit/audit/shop/WLIC">West Lake iCollection</a>[<?php echo $this->count_wlic;?>]</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td><p>Copyright &copy; Phone Collection 2012<br />
    *This form is designed for internal use only<br />
    *Your IP address: recorderd as evidence<br />
    *Do not use this form in any other circumstances , only use this form on the store computer<br />
    *Should you have any problem , please call head office ASAP!</p>
    <p>&nbsp;</p></td>
  </tr>
</table>
</body>
</html>
