<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body style="font-family:Arial, Helvetica, sans-serif">
<table width="300" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td>Date</td>
    <td>Code</td>
  </tr>
<?php
//$date = "";
$code = "";

foreach($this->list as $k => $v){
	var_dump($v);
if($v["remark_status"]!=$code){
?>  
  <tr>
    <td><?=$v["date_record"]?></td>
    <td><a href="faultyaudit/list-status-detail/code/<?=$v["remark_status"]?>"><?=$v["remark_status"]?></a></td>
  </tr>
<?php
$code = $v["remark_status"];
}
}
?>
</table>
</body>
</html>
