<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
<!--
.Table1px {}{
  border-collapse:collapse;
  border: none;
  background: #FFFFFF;
  table-layout:fixed;
}
.Table1px th {}{
  border: solid 1px #000000;
}
.Table1px td {}{
  border: solid 1px #000000;
}
-->
</style>
</head>
<body style="font-family:Arial, Helvetica, sans-serif; font-size:12px;">
<h1>Will Rjected Product List </h1>
1) Select Product:
<form action="/faultyaudit/save-reject-list" method="post">
<table width="1000" border="1" cellspacing="0" cellpadding="5" class="Table1px">
  <tr>
    <td><input type="checkbox" onClick="toggle(this)" />
    All / None</td>
    <td>ID</td>
    <td>Shop Code</td>
    <td>Barcode</td>
    <td style="width:200px;">Name</td>
    <td>Date of Audit</td>
    <td style="width:200px;">Why Reject</td>

  </tr>
<?php
foreach($this->rejectList as $k => $v){
?>  
  <tr>
      <td><input name="arr_action[]" type="checkbox" value="<?=$v["id_faulty"]?>" /></td>
    <td>#<?=$v["id_faulty"]?></td>
    <td><?=$v["shopcode_faulty"]?></td>
    <td><?=$v["product_code_faulty"]?></td>
    <td><?=$v["product_name_faulty"]?></td>
    <td><?=$v["date_faulty"]?></td>
    <td><?=$v["audit_comment"]?></td>

  </tr>
<?php
}
?>
  <tr>
    <td><input type="checkbox" onClick="toggle(this)" />
    All / None</td>  
    <td>ID</td>
    <td>Shop Code</td>
    <td>Barcode</td>
    <td style="width:200px;">Name</td>
    <td>Date of Audit</td>
    <td style="width:200px;">Why Reject</td>
  </tr>
</table>
<br />
2) Select Method/Condition
<br />
<br />
<input type="radio" name="faulty_handle" id="faulty_handle1" value="200" checked="checked" />
We have &quot;Returned&quot; these faultys back to shop next week<br />
<br />
<input type="radio" name="faulty_handle" id="faulty_handle2" value="201" />
We &quot;Never Receive&quot; these faultys
<br />
<br />
3)Confirm and Print Summary
<br />
<br />
Auditor Name :
<input name="staff_name" type="text" id="staff_name" value="Flora" />
<br />
<br />
<input name="go" type="submit" value="Confirm Take Action" id="go" />
</form>
</body>
</html>
