<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif; font-size:11px;">
<h3><?=$this->fdpNo?>
<br />
Dispose List Dispose date: <?=$this->date?> Sign By:__________________ </h3>
<table width="650" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td style="width:100px;">RMA ID</td>
    <td>BarCode</td>
    <td style="width:350px;">Name</td>
    <td style="width:50px;">Qty</td>
  </tr>
<?php 

$faultyProduct = new Model_DbTable_Faultyproduct();
foreach($_POST["arr_action"] as $k => $v){
$fpRow = $faultyProduct->getFaultyProduct($v);	

?>
  <tr>
    <td>#<?=$v?></td>
    <td><?=$fpRow["product_code_faulty"]?></td>
    <td><?=$fpRow["product_name_faulty"]?></td>
    <td><?=$fpRow["faulty_qty"]?></td>
  </tr>
<?php }?>
</table>
</body>
</html>
