<!DOCTYPE html>
<html lang="en">
<head>
	
	<!-- start: Meta -->
	<meta charset="utf-8">
	<title>Phone Collection iCollection </title>
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: CSS -->
	<link id="bootstrap-style" href="/skin/css/bootstrap.min.css" rel="stylesheet">
	<link href="/skin/css/bootstrap-responsive.min.css" rel="stylesheet">
	<link id="base-style" href="/skin/css/style.css" rel="stylesheet">
	<link id="base-style-responsive" href="/skin/css/style-responsive.css" rel="stylesheet">
	
	<!--[if lt IE 7 ]>
	<link id="ie-style" href="/skin/css/style-ie.css" rel="stylesheet">
	<![endif]-->
	<!--[if IE 8 ]>
	<link id="ie-style" href="/skin/css/style-ie.css" rel="stylesheet">
	<![endif]-->
	<!--[if IE 9 ]>
	<![endif]-->
	
	<!-- end: CSS -->
	

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- start: Favicon -->
	<link rel="shortcut icon" href="/skin/img/favicon.ico">
	<!-- end: Favicon -->
	
		
		
		
</head>

<body>
		<div id="overlay">
		<ul>
		  <li class="li1"></li>
		  <li class="li2"></li>
		  <li class="li3"></li>
		  <li class="li4"></li>
		  <li class="li5"></li>
		  <li class="li6"></li>
		</ul>
	</div>	
	<!-- start: Header -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="index.html"><!--  <img alt="Perfectum Dashboard" src="/skin/img/logo20.png" /> <span class="hidden-phone">Perfectum Dashboard</span> --></a>
								
				<!-- start: Header Menu -->
				<div class="nav-no-collapse header-nav">
					<ul class="nav pull-right">
						
						<!-- start: Notifications Dropdown -->
						
						<!-- end: Notifications Dropdown -->
						<!-- start: Message Dropdown -->
						
						<!-- end: Message Dropdown -->
						
						<!-- start: User Dropdown -->
						<li class="dropdown">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="icon-user icon-white"></i>
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="#"><i class="icon-user"></i> Profile</a></li>
								<li><a href="login.html"><i class="icon-off"></i> Logout</a></li>
							</ul>
						</li>
						<!-- end: User Dropdown -->
					</ul>
				</div>
				<!-- end: Header Menu -->
				
			</div>
		</div>
	</div>
	<!-- start: Header -->
	
		<div class="container-fluid">
		<div class="row-fluid">
				
			<!-- start: Main Menu -->
			<div class="span2 main-menu-span">
				<div class="nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li><a href="index.html"><i class="icon-home icon-white"></i><span class="hidden-tablet"> Dashboard</span></a></li>
                        <li>
							<a class="dropmenu" href="#"><i class="icon-list-alt icon-white"></i><span class="hidden-tablet">Products</span></a>
							<ul>
								<li><a class="submenu" href="/products/list-products"><i class="fa-icon-file-alt"></i><span class="hidden-tablet">Products List</span></a></li>
								<li><a class="submenu" href="/products/list-products-price"><i class="fa-icon-file-alt"></i><span class="hidden-tablet">Products Price</span></a></li>
							</ul>	
						</li>
<li>
							<a class="dropmenu" href="#"><i class="icon-list-alt icon-white"></i><span class="hidden-tablet">Orders</span></a>
							<ul>
								<li><a class="submenu" href="#"><i class="fa-icon-file-alt"></i><span class="hidden-tablet">Order List</span></a></li>
<li><a class="submenu" href="#"><i class="fa-icon-file-alt"></i><span class="hidden-tablet">Search Order</span></a></li>                                
                                <li><a class="submenu" href="#"><i class="fa-icon-file-alt"></i><span class="hidden-tablet">Shipment List</span></a></li>
							</ul>	
						</li>                        
                        <li><a href="/products/import"><i class="icon-tasks icon-white"></i><span class="hidden-tablet">Import</span></a></li>
						
					</ul>
				</div><!--/.well -->
			</div><!--/span-->
			<!-- end: Main Menu -->
			
			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			
			<div id="content" class="span10" style="min-height:1000px;">
			<!-- start: Content -->
			
			<div>
				<hr>
				<ul class="breadcrumb">
					<li>
						<a href="#">Home</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="#">Path</a>
					</li>
				</ul>
				<hr>
			</div>

			<div class="row-fluid sortable">

			<?php echo $this->layout()->content ?>
			

            </div>
    		<hr>
			<!-- end: Content -->
			</div><!--/#content.span10-->
				</div><!--/fluid-row-->
				


		
		<div class="clearfix"></div>
		
		<footer>
			<p>
				<span style="text-align:left;float:left">&copy; <a href="http://clabs.co" target="_blank">creativeLabs</a> 2013</span>
				<span style="text-align:right;float:right">Powered by: <a href="#">Perfectum Dashboard</a></span>
			</p>

		</footer>
				
	</div><!--/.fluid-container-->

	<!-- start: JavaScript-->

		<script src="/skin/js/jquery-1.9.1.min.js"></script>
	<script src="/skin/js/jquery-migrate-1.0.0.min.js"></script>
	
		<script src="/skin/js/jquery-ui-1.10.0.custom.min.js"></script>
	
		<script src="/skin/js/jquery.ui.touch-punch.js"></script>
	
		<script src="/skin/js/bootstrap.min.js"></script>
	
		<script src="/skin/js/jquery.cookie.js"></script>
	
	<!--	<script src='/skin/js/fullcalendar.min.js'></script> 
	

    
		<script src="/skin/js/excanvas.js"></script>
	<script src="/skin/js/jquery.flot.min.js"></script>
	<script src="/skin/js/jquery.flot.pie.min.js"></script>
	<script src="/skin/js/jquery.flot.stack.js"></script>
	<script src="/skin/js/jquery.flot.resize.min.js"></script>

	-->	
		<script src="/skin/js/jquery.chosen.min.js"></script>
		
		
		<script src="/skin/js/jquery.uniform.min.js"></script> 
		
		<script src="/skin/js/jquery.cleditor.min.js"></script>
	  
		<script src="/skin/js/jquery.noty.js"></script>
	
		<script src="/skin/js/jquery.elfinder.min.js"></script>
	
		<script src="/skin/js/jquery.raty.min.js"></script>
	
		<script src="/skin/js/jquery.iphone.toggle.js"></script>
	
		<script src="/skin/js/jquery.uploadify-3.1.min.js"></script>
	
		<script src="/skin/js/jquery.gritter.min.js"></script>
	
		<script src="/skin/js/jquery.imagesloaded.js"></script>
	
		<script src="/skin/js/jquery.masonry.min.js"></script>
	
		<script src="/skin/js/jquery.knob.js"></script>
	
		<script src="/skin/js/jquery.sparkline.min.js"></script>
		
		
		<script src='/skin/js/jquery.dataTables.min.js'></script>
		
		<script src="/skin/js/custom.js"></script>
		<!-- end: JavaScript-->
	
</body>
</html>
